window.allRestaurantData = [
  {
    "ID": "1",
    "Restaurant_Name": "石岐佬中山菜館",
    "Branch": "張溪店",
    "District": "石岐區",
    "Category": "粵菜",
    "Highlight": "當地實力派排隊王，入口非常美味滋味",
    "Description": "當地實力派排隊王，入口非常美味滋味。以石岐乳鴿聞名，是中山本地人最愛的地道粵菜館。",
    "Address": "中山市石岐街道康華路36號",
    "Avg_Cost": "95",
    "Amap_URL": "https://surl.amap.com/7Opxkqm1392I",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "2",
    "Restaurant_Name": "豐圓軒",
    "Branch": "孫文中路店",
    "District": "石岐區",
    "Category": "粵菜",
    "Highlight": "粵式早茶中的招牌，小食堅守經典的味道",
    "Description": "粵式早茶中的招牌，小食堅守經典的味道。石岐乳鴿、蘆兜糭、三鄉瀨粉均為招牌菜式。",
    "Address": "丰圆轩粤式茶楼(孙文中路店) 孙文东路中港家私大厦",
    "Avg_Cost": "55",
    "Amap_URL": "https://surl.amap.com/7PUB6KCE25b",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "3",
    "Restaurant_Name": "德雲軒",
    "Branch": "石岐店",
    "District": "石岐區",
    "Category": "粵菜",
    "Highlight": "在業界享有盛名，主打傳統風味的粵式早茶",
    "Description": "在業界享有盛名，主打傳統風味的粵式早茶。石岐乳鴿、小欖炸魚球、瑤柱蒸魚腩均為招牌菜式。",
    "Address": "中山市豪程路16号2栋3卡(福兴花园内)",
    "Avg_Cost": "50",
    "Amap_URL": "https://surl.amap.com/IRxPWK183X4",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "4",
    "Restaurant_Name": "大墩榮記食店",
    "Branch": "",
    "District": "石岐區",
    "Category": "家常菜",
    "Highlight": "被本地人封神的深夜食堂，烹調火候恰到好處",
    "Description": "被本地人封神的深夜食堂，烹調火候恰到好處。沙溪扣肉、中山粉果金吒（每日限量）是必點招牌。",
    "Address": "中山市石岐街道大墩村47号之一",
    "Avg_Cost": "60",
    "Amap_URL": "https://surl.amap.com/a6VjQgu1t9lY",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "5",
    "Restaurant_Name": "根叔店",
    "Branch": "逢源商業街店",
    "District": "石岐區",
    "Category": "燒烤",
    "Highlight": "燒烤愛好者的不二之選，各式肉串味道一絕",
    "Description": "燒烤愛好者的不二之選，各式肉串味道一絕。石岐乳鴿、三鄉瀨粉為招牌菜式。",
    "Address": "石岐区街道悦来路2号九曲城",
    "Avg_Cost": "",
    "Amap_URL": "https://surl.amap.com/7QtkRwSQ1E2",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "6",
    "Restaurant_Name": "喜珍軒",
    "Branch": "",
    "District": "石岐區",
    "Category": "粵菜",
    "Highlight": "高質粵菜風味上佳，精緻味美",
    "Description": "高質粵菜風味上佳，精緻味美。位於中山喜來登酒店二層，石岐乳鴿、小欖炸魚球、龍蝦粥為招牌菜式。",
    "Address": "中山市中山喜來登酒店二層 喜珍轩",
    "Avg_Cost": "100",
    "Amap_URL": "https://surl.amap.com/ajlCors11edv",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "7",
    "Restaurant_Name": "岐香村",
    "Branch": "",
    "District": "石岐區",
    "Category": "滷水",
    "Highlight": "大隱於世的口碑滷水店，滷味非常入味",
    "Description": "大隱於世的口碑滷水店，滷味非常入味。石岐乳鴿、三鄉瀨粉為招牌菜式。",
    "Address": "中山市蓮興路4號寶麗閣1-2號",
    "Avg_Cost": "",
    "Amap_URL": "https://surl.amap.com/7SyvzAKxeaO",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "8",
    "Restaurant_Name": "紅日飯店",
    "Branch": "裕隆三路店",
    "District": "石岐區",
    "Category": "粵菜",
    "Highlight": "主打脆肉鯇的地道名店，爽脆魚肉一口驚豔",
    "Description": "主打脆肉鯇的地道名店，爽脆魚肉一口驚豔。脆肉鯇、小欖炸魚球、三鄉瀨粉、沙溪牛腩均為招牌菜式。",
    "Address": "中山市裕隆三路37号",
    "Avg_Cost": "95",
    "Amap_URL": "https://surl.amap.com/3mFUx7E170ja",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "9",
    "Restaurant_Name": "海港城海鮮大酒樓",
    "Branch": "東區店",
    "District": "東區",
    "Category": "海鮮酒樓",
    "Highlight": "馳名酒樓值得專程打卡，匠心烹呈粵式海鮮菜",
    "Description": "馳名酒樓值得專程打卡，匠心烹呈粵式海鮮菜。海鮮刺身、龍蝦粥、蒜蓉粉絲扇貝為招牌菜式。",
    "Address": "中山市東區街道中山五路65號",
    "Avg_Cost": "85",
    "Amap_URL": "https://surl.amap.com/Hq41kic8kj",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "10",
    "Restaurant_Name": "金匯酒樓",
    "Branch": "中山東區店",
    "District": "東區",
    "Category": "粵菜",
    "Highlight": "頗具名氣的本土餐廳，細緻烹飪打造中山美食",
    "Description": "頗具名氣的本土餐廳，細緻烹飪打造中山美食。三鄉瀨粉、脆肉鯇為招牌菜式。",
    "Address": "中山市中山三路16號利和廣場6-8樓",
    "Avg_Cost": "105",
    "Amap_URL": "https://surl.amap.com/74T2MC699QD",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "11",
    "Restaurant_Name": "品小館",
    "Branch": "東區",
    "District": "東區",
    "Category": "粵菜",
    "Highlight": "好評如潮的地道小館，豐富菜式展現粵菜的奧妙",
    "Description": "好評如潮的地道小館，豐富菜式展現粵菜的奧妙。石岐乳鴿、沙溪扣肉為招牌菜式。",
    "Address": "中山市中山五路2號紫馬奔騰廣場3樓15號商鋪",
    "Avg_Cost": "95",
    "Amap_URL": "https://surl.amap.com/75BtOgG1172u",
    "Status": "https://www.facebook.com/share/p/1HNo5EbhaD/",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "12",
    "Restaurant_Name": "逸峯特色中餐廳及酒吧",
    "Branch": "東區（威斯汀酒店40樓）",
    "District": "東區",
    "Category": "粵菜",
    "Highlight": "高空之上的雅致之所，高顏值粵菜出品不俗",
    "Description": "高空之上的雅致之所，高顏值粵菜出品不俗。位於威斯汀酒店40樓，石岐乳鴿、龍蝦粥為招牌菜式。",
    "Address": "中山市同興路98號中山利和威斯汀酒店40樓",
    "Avg_Cost": "155",
    "Amap_URL": "https://surl.amap.com/8SCIPr8162lU",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "13",
    "Restaurant_Name": "軒記餐廳",
    "Branch": "西區彩虹店",
    "District": "西區",
    "Category": "粵菜",
    "Highlight": "始於1981年的老店，鳳梨包可謂百吃不厭",
    "Description": "始於1981年的老店，鳳梨包可謂百吃不厭。三鄉瀨粉、小欖炸魚球、豉油皇炒麵均為招牌菜式。",
    "Address": "中山市彩虹大道20號（近星辰廣場、大信新家園、彩虹市場）",
    "Avg_Cost": "80",
    "Amap_URL": "https://surl.amap.com/96KJN9MMahn",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "14",
    "Restaurant_Name": "香山家宴",
    "Branch": "西區（彩虹大道）",
    "District": "西區",
    "Category": "粵菜",
    "Highlight": "中式庭院內的粵菜名館，菜餚盡顯當地特色",
    "Description": "中式庭院內的粵菜名館，菜餚盡顯當地特色。脆肉鯇、蕉蕾粥、瑤柱蘑菇燉雞、中山粉果均為招牌菜式。",
    "Address": "中山市彩虹大道167號荔景苑內",
    "Avg_Cost": "140",
    "Amap_URL": "https://surl.amap.com/97BNnn4Y2Hw",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "15",
    "Restaurant_Name": "爱群食店(银潭二路)",
    "Branch": "銀潭二路店",
    "District": "南區",
    "Category": "粵菜",
    "Highlight": "體驗早茶文化的寶地，粵式茶點均為手工製作",
    "Description": "體驗早茶文化的寶地，粵式茶點均為手工製作。三鄉瀨粉、鹽焗雞、脆肉鯇均為招牌菜式。",
    "Address": "中山市银谭二路25-27号",
    "Avg_Cost": "55",
    "Amap_URL": "https://surl.amap.com/F6t7Cm11aq2",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "17",
    "Restaurant_Name": "荔苑隆都菜館",
    "Branch": "沙溪店",
    "District": "沙溪鎮",
    "Category": "沙溪菜",
    "Highlight": "餐廳以沙溪風味著稱，鎮店名菜是荔枝木燒雞",
    "Description": "餐廳以沙溪風味著稱，鎮店名菜是荔枝木燒雞。沙溪扣肉、中山粉果金吒、花雕酒雞均為招牌菜式。",
    "Address": "中山市105國道隆都家私城內",
    "Avg_Cost": "75",
    "Amap_URL": "https://surl.amap.com/9BD5a3g1507P",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "18",
    "Restaurant_Name": "小榄海港大酒楼(海港城店)",
    "Branch": "小欖店",
    "District": "小欖鎮",
    "Category": "粵菜",
    "Highlight": "當地人的宴客勝地，經典粵菜追求至臻至純",
    "Description": "當地人的宴客勝地，經典粵菜追求至臻至純。龍蝦粥、鮑魚撈飯、海鮮燉蛋均為招牌菜式。",
    "Address": "中山市昇平東路1號海港城購物商場6、7樓",
    "Avg_Cost": "125",
    "Amap_URL": "https://surl.amap.com/8yMRbXc1ubLr",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "19",
    "Restaurant_Name": "小欖人家酒樓",
    "Branch": "民安店",
    "District": "小欖鎮",
    "Category": "粵菜",
    "Highlight": "人氣酒樓聲名顯赫，廣府佳餚用時令食材入饌",
    "Description": "人氣酒樓聲名顯赫，廣府佳餚用時令食材入饌。小欖炸魚球、脆肉鯇、鮮蝦滑燒賣均為招牌菜式。",
    "Address": "中山市小榄镇民安中路31号",
    "Avg_Cost": "110",
    "Amap_URL": "https://surl.amap.com/8yY5i7E1i5iR",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "20",
    "Restaurant_Name": "如軒·海鮮砂鍋粥·潮汕菜",
    "Branch": "小欖店",
    "District": "小欖鎮",
    "Category": "潮汕菜",
    "Highlight": "二十餘載不改風味，海鮮砂鍋粥深受食客青睞",
    "Description": "二十餘載不改風味，海鮮砂鍋粥深受食客青睞。砂鍋粥、鮑魚撈飯為招牌菜式。",
    "Address": "中山市民安中路90號",
    "Avg_Cost": "65",
    "Amap_URL": "https://surl.amap.com/8z1WsquA4qg",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "21",
    "Restaurant_Name": "明記食店",
    "Branch": "三角鎮店",
    "District": "三角鎮",
    "Category": "粥麵火鍋",
    "Highlight": "座無虛席的網紅粥火鍋，慢火細煮鮮美滋味",
    "Description": "座無虛席的網紅粥火鍋，慢火細煮鮮美滋味。中山粉果金吒、沙溪扣肉、蜜汁叉燒均為招牌菜式。",
    "Address": "中山市新裕路全一快遞對面",
    "Avg_Cost": "60",
    "Amap_URL": "https://surl.amap.com/89pvh5E1h3sJ",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "22",
    "Restaurant_Name": "樂美中餐廳",
    "Branch": "港口鎮（保利艾美酒店）",
    "District": "港口鎮",
    "Category": "粵菜",
    "Highlight": "精緻粵菜賞心悅目，口味地道的中山美食",
    "Description": "精緻粵菜賞心悅目，口味地道的中山美食。位於中山保利艾美酒店五層，石岐乳鴿、龍蝦粥、脆皮燒肉、櫻花蝦炒飯均為招牌菜式。",
    "Address": "中山市港口大道21號中山保利艾美酒店五層（鄰近保利國際廣場、萬民滙、中山北站）",
    "Avg_Cost": "110",
    "Amap_URL": "https://surl.amap.com/9L7yaOm1d60O",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "23",
    "Restaurant_Name": "浩輝飲食",
    "Branch": "",
    "District": "石岐區",
    "Category": "粥麵小食",
    "Highlight": "明星打卡過的中山老字號，肉丸粥鮮甜紮實",
    "Description": "主營粥粉麵小食，明星打卡過的中山老字號小店。必點招牌肉丸粥，綿稠順滑的粥底，手捏肉丸口感鮮甜紮實，雲吞蝦子麵和牛腩蒸腸粉也很推薦。",
    "Address": "中山市石岐街道南基路步行街大笪地3號",
    "Avg_Cost": "25",
    "Amap_URL": "https://surl.amap.com/4BzVv4C1d3xA",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "24",
    "Restaurant_Name": "正斗面家",
    "Branch": "",
    "District": "石岐區",
    "Category": "粥麵小食",
    "Highlight": "小店擠滿食客，招牌牛三星麵湯底濃郁入味",
    "Description": "正鬥面家雖是小店，卻吸引不少人光顧。招牌牛三星麵（牛腩牛筋牛肚），燉得十分入味，湯底濃郁；雲吞亦是熱門菜品，不少街坊更會購買生雲吞回家烹調。",
    "Address": "中山市石岐街道太平路後崗涌66號",
    "Avg_Cost": "",
    "Amap_URL": "https://surl.amap.com/7UG0cEq1baAn",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "25",
    "Restaurant_Name": "亞金金",
    "Branch": "",
    "District": "石岐區",
    "Category": "粥麵小食",
    "Highlight": "白咖哩海鮮麵獨特惹味，街坊人氣小店",
    "Description": "街坊人氣小店，以白咖哩海鮮麵聞名，湯底濃郁獨特，海鮮新鮮，是中山少見的特色麵食。",
    "Address": "中山市柏苑路157号",
    "Avg_Cost": "",
    "Amap_URL": "https://surl.amap.com/7TT9BuW175HE",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "26",
    "Restaurant_Name": "心意美食(中山市石岐区金顺行店)",
    "Branch": "",
    "District": "石岐區",
    "Category": "粥麵小食",
    "Highlight": "香菜牛肉拉腸獨特惹味，早市必試",
    "Description": "以香菜牛肉拉腸聞名，腸粉滑嫩，配上新鮮香菜與牛肉，口感層次豐富，是中山特色早市小食。",
    "Address": "中山市中山亚太医院北门旁",
    "Avg_Cost": "",
    "Amap_URL": "https://surl.amap.com/7W8MA4i108TB",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "27",
    "Restaurant_Name": "鑷鑷美食",
    "Branch": "",
    "District": "石岐區",
    "Category": "炸物小食",
    "Highlight": "炸物煎釀三寶香脆可口，街坊宵夜首選",
    "Description": "主打炸物和煎釀三寶，食材新鮮，炸至香脆，是中山街坊宵夜的人氣選擇。",
    "Address": "中山市西華社北巷13號",
    "Avg_Cost": "",
    "Amap_URL": "https://surl.amap.com/7XVY1po1o0nP",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "28",
    "Restaurant_Name": "岐贊老鋪·牧場水牛奶",
    "Branch": "",
    "District": "石岐區",
    "Category": "甜品",
    "Highlight": "孫文西路步行街懷舊甜品店，水牛奶特色甜品打卡必試",
    "Description": "位於孫文西路步行街，充滿懷舊氣息的小食甜品店，主打水牛奶特色甜品，包括奶油草莓雙皮奶、金莎脆皮湯圓雙皮奶等，還有厚乳酸奶、鮮乳酪千層酥等多款選擇。",
    "Address": "中山市石岐街道孫文西路31號",
    "Avg_Cost": "25",
    "Amap_URL": "https://surl.amap.com/7Z20ZTk1q6yZ",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "29",
    "Restaurant_Name": "西關樓·嶺南茶樓",
    "Branch": "石岐店",
    "District": "石岐區",
    "Category": "粵菜",
    "Highlight": "精緻粵式點心，創意打卡小吃令人驚喜",
    "Description": "在中山有三家分店，主打精緻粵式點心，除了傳統西關蝦餃皇、豉汁蒸排骨、脆皮紅米腸，還有小黃鴨泡泡浴蛋撻、蘋果造型平安包、鮑魚燒賣等創意打卡小吃。",
    "Address": "中山市石岐區蓮塘路66號",
    "Avg_Cost": "75",
    "Amap_URL": "",
    "Status": "X",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "30",
    "Restaurant_Name": "四囍咖啡",
    "Branch": "",
    "District": "石岐區",
    "Category": "咖啡 Chill 地方",
    "Highlight": "騎樓建築內的復古咖啡店，蜂蜜龜苓膏咖啡獨一無二",
    "Description": "藏在騎樓建築裡，裝修走復古懷舊風格，一秒回到80年代。出品特別，蜂蜜龜苓膏咖啡內有真的龜苓膏；「百年好合」是茉莉花茶加入百合，新鮮配搭，另有簡餐供應。",
    "Address": "中山市孫文中路169號",
    "Avg_Cost": "50",
    "Amap_URL": "https://surl.amap.com/800zufoB22q",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "31",
    "Restaurant_Name": "盞簋品味館",
    "Branch": "東區店",
    "District": "東區",
    "Category": "粵菜",
    "Highlight": "新式隆都菜館，芥末檸檬撈雞甜酸平衡驚艷",
    "Description": "新式隆都菜館，隆都是中山沙溪及大涌兩地的舊稱，當地菜稱為隆都菜。菜式選擇豐富，份量適中，推薦芥末檸檬撈雞、傳統炸肝捲、冬瓜拆魚羹、六十年代隆都炒飯。",
    "Address": "中山市东区东苑路15-17卡(松苑横街7号楼下)",
    "Avg_Cost": "75",
    "Amap_URL": "https://surl.amap.com/76yEhDAv3oN",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "32",
    "Restaurant_Name": "谷·現代粵菜",
    "Branch": "",
    "District": "東區",
    "Category": "粵菜",
    "Highlight": "黑珍珠及米芝蓮推介，中山粵菜「天花板」",
    "Description": "位於萬谷菜籃子廣場頂層，主打精緻時尚粵菜，曾獲黑珍珠及米芝蓮指南推介，被譽為中山粵菜「天花板」。必食魚子醬片皮鴨、黑豚肉叉燒秋梨、野菜石榴包、現代紅燒乳鴿，部分包廂可俯瞰城市景色。",
    "Address": "谷现代粤菜 槎南路9号",
    "Avg_Cost": "180",
    "Amap_URL": "https://surl.amap.com/1LSAwxwggIQ",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "33",
    "Restaurant_Name": "taan叹·糖(华夏小区店)",
    "Branch": "",
    "District": "東區",
    "Category": "甜品",
    "Highlight": "網紅糖水鋪，碧根果綠水鬼（開心果糊）必點",
    "Description": "中山網紅糖水鋪，招牌碧根果綠水鬼（開心果糊）口感濃稠不過甜，吸引不少人慕名而至。焦糖雙皮奶表面燒焦的焦糖搭配正宗雙皮奶，同樣是人氣甜品。",
    "Address": "taan叹·糖(华夏小区店) 中山市华夏小区南1门旁",
    "Avg_Cost": "50",
    "Amap_URL": "https://surl.amap.com/1LMWCZw1kcr8",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "34",
    "Restaurant_Name": "Gettwo xDrink off",
    "Branch": "",
    "District": "東區",
    "Category": "咖啡 Chill 地方",
    "Highlight": "美式復古工業風打卡咖啡店，創意飲品食物令人驚喜",
    "Description": "位於中山東區的美式快餐店，採用美式復古工業風格裝潢，宛如置身LA。提供咖啡、主食、漢堡、小食及特色飲品，招牌有三眼仔造型抹茶牛角仔、猛男Kitty特飲、超大牛角豬扒包。",
    "Address": "Get two(东区店) 中山市東區街道柏苑寶麗坊6棟1-2號",
    "Avg_Cost": "50",
    "Amap_URL": "https://surl.amap.com/7kZQMGu3fmn",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "35",
    "Restaurant_Name": "荷利炸物·日式炸牛排",
    "Branch": "",
    "District": "東區",
    "Category": "日式料理",
    "Highlight": "高CP值日式石燒炸牛扒定食，迷你石燒爐自調熟度",
    "Description": "主打高CP值的日式石燒炸牛扒定食，提供黑松露霜降牛排定食、石燒牛排、芝士牛肉漢堡排定食等，可在迷你石燒爐自行調整熟度。另有咖喱炸雞飯、銷魂牛玉飯等選擇。",
    "Address": "荷利炸物·日式炸牛排专门店 石岐街道大信新都匯蓮塘東路11號13-14號鋪",
    "Avg_Cost": "100",
    "Amap_URL": "https://surl.amap.com/7mtyE66Fdkq",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "36",
    "Restaurant_Name": "漁越·創意日式料理",
    "Branch": "",
    "District": "東區",
    "Category": "日式料理",
    "Highlight": "高品質高性價比壽司，食材新鮮分量十足",
    "Description": "中山極受歡迎的日式料理店，以提供高品質及高性價比的壽司而聞名。食材新鮮分量十足，必食厚切三文魚腩壽司、招牌火炙手握鵝肝壽司、阿根廷極鮮原隻手握紅蝦壽司。",
    "Address": "中山市團結路11號佳樂公寓34卡",
    "Avg_Cost": "75",
    "Amap_URL": "https://surl.amap.com/7l87Wv8ZcoS",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "37",
    "Restaurant_Name": "賀禧·Omakase·燒鳥",
    "Branch": "",
    "District": "東區",
    "Category": "日式料理",
    "Highlight": "港人推薦的高級日式燒鳥Omakase，炭火烹調近距離欣賞",
    "Description": "不少香港人推薦的中山高級日式料理店，主打燒鳥與廚師發辦。半開放式廚房可近距離觀賞主廚在炭火上準備食材。必食炭火燒鳥拼盤、刺身拼盤、海膽和牛卷、燒雞皮、醬油漬左口魚壽司。",
    "Address": "中山市東區興文路118號御峰臻品花園2幢8-9卡",
    "Avg_Cost": "275",
    "Amap_URL": "https://surl.amap.com/8ZWpi3AP5Xy",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "38",
    "Restaurant_Name": "煲煲掂风味煲仔饭餐厅(西区店)",
    "Branch": "西區店",
    "District": "西區",
    "Category": "粵菜",
    "Highlight": "中山老牌煲仔飯，平價實惠的街坊飯堂",
    "Description": "中山老牌煲仔飯店，走平價實惠街坊路線，招牌鮮嫩多汁的妙齡乳鴿和特色煲仔飯只需¥20-30，老火燉湯¥20有找，是不少本地人的街坊飯堂。",
    "Address": "中山市中山一路109号(国际酒店对面入内)",
    "Avg_Cost": "60",
    "Amap_URL": "https://surl.amap.com/99MOc0qSgyw",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "39",
    "Restaurant_Name": "粤禧顺·广东顺德菜(西区店)",
    "Branch": "西區店",
    "District": "西區",
    "Category": "順德菜",
    "Highlight": "在中山吃到地道順德菜，八彩撈雞食過返尋味",
    "Description": "在中山都能吃到地道順德菜，粵禧順在中山有不少分店。招牌順德八彩撈雞採用新鮮文昌雞，肉質鮮嫩，輔以八種佐料口感豐富，食過返尋味。",
    "Address": "中山市翠虹路19号招商映月台正门右侧",
    "Avg_Cost": "60",
    "Amap_URL": "https://surl.amap.com/1Lf972eueAl",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "40",
    "Restaurant_Name": "丰裕湾脆鲩鱼(南区店)",
    "Branch": "",
    "District": "南區",
    "Category": "粵菜",
    "Highlight": "大眾點評必吃榜，脆肉鯇一魚多吃活魚現切",
    "Description": "大眾點評必吃榜上榜餐廳，脆肉鯇一魚多吃非常受歡迎，全部活魚現切保證新鮮。不一樣的鮮味清水火鍋，魚片魚柳鮮嫩脆彈幾秒就能吃，「豉汁蒸脆魚腩」魚腩肉Q彈嫩滑。",
    "Address": "中山市南区街道悦来南路悦乐街3号1-2幢7卡商铺(近天虹购物中心)",
    "Avg_Cost": "85",
    "Amap_URL": "https://surl.amap.com/1MKwuf41m15E",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "41",
    "Restaurant_Name": "綠野仙蹤生態食府",
    "Branch": "",
    "District": "南區",
    "Category": "農家菜",
    "Highlight": "詹園附近原生態農莊，荔枝木燒鵝古法炮製打卡",
    "Description": "就在詹園附近的中山南區本地原生態農莊，招牌荔枝木燒鵝、鮑汁豆腐基本每桌必點，食材新鮮味道佳，荔枝木燒鵝的古法炮製過程還可以拍照打卡。不僅有農家菜，還有農場、草莓園、兒童樂園等。",
    "Address": "中山市美升家居有限公司南50米(曹边工业大道南)",
    "Avg_Cost": "110",
    "Amap_URL": "https://surl.amap.com/6QBMc8W1naO9",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "42",
    "Restaurant_Name": "崖口煲仔飯",
    "Branch": "",
    "District": "南區",
    "Category": "煲仔飯",
    "Highlight": "選用崖口米，一鍋四肉煲仔飯香味濃郁",
    "Description": "中山崖口米超出名，崖口煲仔飯選用口感綿滑的崖口米，色澤透亮、香味濃郁。煲仔飯食材可自選拼配，一鍋四肉，口味豐富，肉香撲鼻，性價比高。夏天不遠處有網紅稻田海、絕美海堤打卡。",
    "Address": "中山市南区街道寮后村龙子街2号地铺",
    "Avg_Cost": "35",
    "Amap_URL": "https://surl.amap.com/9uOGsMqB6lY",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "43",
    "Restaurant_Name": "Old Boy Coffeecake",
    "Branch": "",
    "District": "南朗鎮",
    "Category": "咖啡 Chill 地方",
    "Highlight": "四季稻田景觀網紅咖啡店，限量手工蛋糕精緻可愛",
    "Description": "位於中山南朗的網紅咖啡店，擁有四季稻田景觀及多面落地大玻璃窗，完美融入大自然。蛋糕每日限量手工製作，甜度及分量都剛剛好，造型精緻可愛，十分打卡able。",
    "Address": "中山市南朗镇崖口新村街12巷7号",
    "Avg_Cost": "45",
    "Amap_URL": "https://surl.amap.com/9xqkmJY130Ny",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "44",
    "Restaurant_Name": "上上簽私夥",
    "Branch": "",
    "District": "沙溪鎮",
    "Category": "私房菜",
    "Highlight": "沙溪騎樓8年私房菜，復古設計配創新菜式出片又好吃",
    "Description": "沙溪騎樓裏開了8年的私房菜，裝修溫馨別致，復古設計與創新私房菜碰撞別有風味。招積大蝦、招牌紫蘇茄瓜、藥膳紫蘇浸沙溪牛肉均是特色菜式，好吃又出片。",
    "Address": "中山市沙溪鎮港頭大街61號",
    "Avg_Cost": "75",
    "Amap_URL": "https://surl.amap.com/9BHsDtEXgg0",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "45",
    "Restaurant_Name": "恒記鯽魚粥",
    "Branch": "",
    "District": "沙溪鎮",
    "Category": "粥麵小食",
    "Highlight": "沙溪本地老字號，鯽魚粥清甜暖胃，糕點點心搶手",
    "Description": "沙溪本地村民從小吃到大的老字號，親民價格味道超正，開在村巷裏。2條魚起片熬粥，魚肉不腥味道清甜很暖胃。除了鯽魚粥，沙溪角仔、芋頭糕、木薯煎堆等各種糕點點心也很搶手。",
    "Address": "中山市沙溪镇岗背菜市场上陆幼儿园前",
    "Avg_Cost": "40",
    "Amap_URL": "https://surl.amap.com/9DFhFICP3IP",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "46",
    "Restaurant_Name": "Amorning Cafe",
    "Branch": "沙溪店",
    "District": "沙溪鎮",
    "Category": "咖啡 Chill 地方",
    "Highlight": "古老社區內的韓系精品咖啡店，特色造型麵包打卡必試",
    "Description": "坐落於古老社區內，融合簡約奶油及復古風格的韓系精品咖啡店。除了高品質咖啡，推出多款特色造型麵包，包括小熊麵包、小狗牛角包、荷包蛋小麵包、冰淇淋香草磅蛋糕、田園風提拉米蘇等。",
    "Address": "中山市沙溪镇龙瑞村探花及第牌坊",
    "Avg_Cost": "45",
    "Amap_URL": "https://surl.amap.com/9FPaPW2cdlU",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "47",
    "Restaurant_Name": "鴿譽軒·藥膳鴿火鍋",
    "Branch": "",
    "District": "小欖鎮",
    "Category": "火鍋",
    "Highlight": "始創1988年三代傳承，藥膳鴿火鍋滋補又美味",
    "Description": "始創於1988年的「鴿譽軒」，招牌是三代傳承的藥膳鴿，濃郁藥材香的藥膳湯，鴿肉鮮嫩，滋補又美味。脆皮紅燒鴿皮酥肉嫩，還有創新做法的「錫紙啫啫鴿」，鴿肉焦香裡嫩，值得一試。",
    "Address": "中山市小欖鎮廣成路66號",
    "Avg_Cost": "80",
    "Amap_URL": "https://surl.amap.com/1EbWGHst7I0",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "48",
    "Restaurant_Name": "金山記靚雞專門店",
    "Branch": "",
    "District": "小欖鎮",
    "Category": "粵菜",
    "Highlight": "新式粵菜風格，無花果菊花雞清甜嫩滑必點",
    "Description": "重新裝修後的金山記，新式粵菜風格，環境舒適。除了乳鴿，醇香鮮甜的各式招牌雞煲也是必點菜。「無花果菊花雞」以礦泉水湯底、新鮮無花果、菊花烹調自家養殖的雞肉，香氣撲鼻，清甜嫩滑。",
    "Address": "中山市石歧街道湖濱中路66號",
    "Avg_Cost": "60",
    "Amap_URL": "https://surl.amap.com/9AIVP9A14fqM",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "49",
    "Restaurant_Name": "馬喜鴿·吃鴿大排檔",
    "Branch": "",
    "District": "石岐區",
    "Category": "粵菜",
    "Highlight": "夜市鴿肉大排檔，多種鴿肉做法熱鬧非凡",
    "Description": "主打夜市鴿肉的大排檔，提供多種鴿肉做法，包括紅燒鴿、鹽焗鴿、鴿粥等，是中山夜市文化的代表，熱鬧非凡，性價比高。",
    "Address": "中山市石岐街道博爱三路36号之一3、4、5、6卡",
    "Avg_Cost": "",
    "Amap_URL": "https://surl.amap.com/8CvAgCS1hbka",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "50",
    "Restaurant_Name": "乾林炒雞",
    "Branch": "",
    "District": "小欖鎮",
    "Category": "粵菜",
    "Highlight": "炒雞香辣鮮嫩，雞血炒飯獨特惹味",
    "Description": "主打炒雞的特色餐廳，炒雞香辣鮮嫩，口感豐富。招牌雞血炒飯獨特惹味，是中山少見的特色菜式，深受本地食客喜愛。",
    "Address": "中山市民新路北83號",
    "Avg_Cost": "",
    "Amap_URL": "https://surl.amap.com/8B3vWJQ174fZ",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "52",
    "Restaurant_Name": "銘珠粥粉",
    "Branch": "",
    "District": "三鄉鎮",
    "Category": "粥麵小食",
    "Highlight": "開業45年三鄉瀨粉老字號，湯底以豬骨雞熬製",
    "Description": "來到中山三鄉不得不試三鄉瀨粉，銘珠粥粉是一間老字號瀨粉店，至今已開業45年，也是不少當地人經常光顧的老店。湯底以新鮮豬骨及雞熬製而成，配料有滑雞、瘦肉、燒鴨、邊肉等可自行搭配。",
    "Address": "中山市三鄉鎮烏石大街3號",
    "Avg_Cost": "",
    "Amap_URL": "https://surl.amap.com/882w48Wm3Au",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "53",
    "Restaurant_Name": "信和堂",
    "Branch": "",
    "District": "三鄉鎮",
    "Category": "甜品",
    "Highlight": "三鄉老字號涼茶鋪，豆撻（黑糖豆花）豆香十足",
    "Description": "三鄉一間老字號涼茶鋪，除了各式傳統涼茶，店內還有糖水、小吃等食品，主要走養生路線。人氣最高的是「豆撻」（黑糖豆花），豆香十足口感順滑。薑汁撞奶、陳皮綠豆沙、紅糖薑棗茶都十分足料。",
    "Address": "中山市三鄉鎮商業街11號",
    "Avg_Cost": "",
    "Amap_URL": "https://surl.amap.com/885ZjCinfTQ",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "54",
    "Restaurant_Name": "日记煲仔饭(景哥食店)",
    "Branch": "",
    "District": "港口鎮",
    "Category": "煲仔飯",
    "Highlight": "港口鎮人氣煲仔飯，食材豐富香味濃郁",
    "Description": "港口鎮人氣煲仔飯店，食材豐富，煲仔飯香味濃郁，是當地街坊的日常飯堂，性價比高，深受本地人喜愛。",
    "Address": "中山市港口鎮浪湧尾街8號",
    "Avg_Cost": "",
    "Amap_URL": "https://surl.amap.com/9OxRxQmA8eA",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "55",
    "Restaurant_Name": "西关楼(万民汇MO CITY店)",
    "Branch": "港口鎮店",
    "District": "港口鎮",
    "Category": "粵菜",
    "Highlight": "精緻粵式點心，創意打卡小吃令人驚喜",
    "Description": "在中山有三家分店，主打精緻粵式點心，除了傳統西關蝦餃皇、豉汁蒸排骨、脆皮紅米腸，還有小黃鴨泡泡浴蛋撻、蘋果造型平安包、鮑魚燒賣等創意打卡小吃。",
    "Address": "中山市港口鎮港口市場萬民匯4樓",
    "Avg_Cost": "75",
    "Amap_URL": "https://surl.amap.com/9Qm1phw1w1dH",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "56",
    "Restaurant_Name": "你好海鮮煲仔粥",
    "Branch": "",
    "District": "坦洲鎮",
    "Category": "海鮮粥",
    "Highlight": "大眾點評必吃榜，海鮮生猛按盤收費最貴¥15",
    "Description": "大眾點評必吃榜上榜餐廳，走街坊大排檔風格，性價比很高。海鮮生猛，食材新鮮又多，海星、小青龍、大魷魚、花蟹、生蠔、鯊魚肚等應有盡有，按盤型收費，最貴一盤僅¥15，在坦洲當地超火爆。",
    "Address": "中山市坦洲鎮神農路12號同勝商業街21卡、25卡",
    "Avg_Cost": "80",
    "Amap_URL": "https://surl.amap.com/aHRvaCC1s1Q9",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "57",
    "Restaurant_Name": "俠成水上農莊",
    "Branch": "",
    "District": "坦洲鎮",
    "Category": "農家菜",
    "Highlight": "坦洲著名農莊，秋冬佛跳墻及古法燒雞人氣極高",
    "Description": "這間農莊在坦洲很出名，不少珠海朋友都會慕名前來，主打中山特色粵菜，當地農家菜、古法燒雞、山水豆腐，平價又好吃。秋冬季節超多人來打卡招牌佛跳墻，營養豐富濃郁鮮甜。",
    "Address": "中山市坦洲鎮工業大道合勝新一村（合勝小學旁）",
    "Avg_Cost": "90",
    "Amap_URL": "https://surl.amap.com/aJmuKNQEa9C",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "58",
    "Restaurant_Name": "紅灣酒樓",
    "Branch": "",
    "District": "黃圃鎮",
    "Category": "粵菜",
    "Highlight": "花園式酒樓逾1200個餐位，嶺南建築環境獨特",
    "Description": "中山市黃圃鎮著名花園式酒樓，設有2個宴會廳和34間不同風格房間，以嶺南建築風格設計，荷塘、芭蕉、凤眼果、龍眼樹營造農家特色環境。菜品以粵菜為主，首創蠶蛹餅別具一格。",
    "Address": "中山市横石路1号",
    "Avg_Cost": "",
    "Amap_URL": "https://surl.amap.com/9Uf0a1A1d3jW",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "59",
    "Restaurant_Name": "粵得軒酒樓",
    "Branch": "",
    "District": "東鳳鎮",
    "Category": "粵菜",
    "Highlight": "招牌黃鱔羹及孜然烤黑毛豬雪花排，傳統手工匠心烹飪",
    "Description": "坐落於東鳳鎮的傳統粵菜酒樓，環境優雅，服務周到，菜品別具一格。秉承傳統手工製作，匠心烹飪，招牌黃鱔羹、孜然烤黑毛豬雪花排、花膠珍菌釀豬肚，每一口都帶來深沉獨特的滋味。",
    "Address": "中山市东凤镇维纳斯皇家酒店三层",
    "Avg_Cost": "",
    "Amap_URL": "https://surl.amap.com/9UvYuyS1A9s0",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "60",
    "Restaurant_Name": "海港大酒楼(南朗兴和广场店)",
    "Branch": "",
    "District": "南朗鎮",
    "Category": "粵菜",
    "Highlight": "首創火焰香茅鴿，廣式早茶精品粵菜融合中西日泰菜式",
    "Description": "南朗海港大酒樓成立於2016年，主營廣式早茶、精品粵菜、特色風味，出品集中、西、日、泰菜式為一身，既堅持中山本土特色，也大力創新融合各地風味，廣受本地食客與旅遊食客喜愛。",
    "Address": "中山市翠亨新區（南朗街道）嶺南路62號興和廣場五樓一卡",
    "Avg_Cost": "",
    "Amap_URL": "https://surl.amap.com/ajOGZrI1a2pF",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "61",
    "Restaurant_Name": "崖口人家海鮮餐廳",
    "Branch": "",
    "District": "南朗鎮",
    "Category": "海鮮酒樓",
    "Highlight": "珠三角馳名崖口青蟹，香茅焗奄仔蟹鮮美絕倫",
    "Description": "成立於2011年，位於南朗街道崖口村沙頭涌，地處咸淡水交界處，盛產各種海鮮，崖口青蟹肉質肥美、體型魁梧、肉多殼薄，享譽珠三角。憑海臨風，吃著海鮮，看著紅樹林隨風搖曳，景色怡人。",
    "Address": "中山市翠亨新區（南朗街道）崖口村沙頭涌崖口人家",
    "Avg_Cost": "",
    "Amap_URL": "https://surl.amap.com/aiSqK1QJe17",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "62",
    "Restaurant_Name": "貝里鄉野農莊（胡鬚佬炒雞）",
    "Branch": "",
    "District": "南朗鎮",
    "Category": "農家菜",
    "Highlight": "19年情懷老店，現殺自養土雞皮脆多汁俘獲食客芳心",
    "Description": "又名胡鬚佬炒雞，位於南朗街道徐劉村公交站旁，是經營了19年的情懷老店。招牌胡鬚佬炒雞選用現殺自養土雞，配上老闆多年炒雞訣竅，皮脆多汁、爽口嫩滑，成功俘獲一眾食客芳心。",
    "Address": "中山市南朗镇贝里老人中心旁",
    "Avg_Cost": "",
    "Amap_URL": "https://surl.amap.com/ajtB82mo0Qt",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "63",
    "Restaurant_Name": "龍泉家宴",
    "Branch": "",
    "District": "五桂山鎮",
    "Category": "客家菜",
    "Highlight": "古木參天山水畫境，客家咸雞到中山烤乳鴿各具匠心",
    "Description": "龍泉家宴精選中山各鎮街特色名菜，從鮮嫩的客家咸雞到脆香流汁的中山烤乳鴿，每一道菜都是對傳統手藝的致敬與創新。餐桌間古木參天，光影斑駁，讓人在品嘗美食的同時，仿佛置身於一幅流動的山水畫中。",
    "Address": "中山市五桂山街道長命水村石榴坑新街20號",
    "Avg_Cost": "",
    "Amap_URL": "https://surl.amap.com/8H6NsAq1odRJ",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "64",
    "Restaurant_Name": "客家庄土樓食府 (五桂山客家庄)",
    "Branch": "",
    "District": "五桂山鎮",
    "Category": "客家菜",
    "Highlight": "氣勢磅礴客家圍屋，土茯苓豬骨湯荔枝柴燒雞原汁原味",
    "Description": "客家庄土樓食府是一座氣勢磅礴的客家圍屋，樓高三層，直徑42米，總建築面積達2000多平方米，有66間廳房。土茯苓豬骨湯、荔枝柴燒雞、豬牛雙丸煲、客家咸雞、客家釀三寶、客家茶果，原汁原味的客家特色美食千萬不能錯過。",
    "Address": "中山市五桂山南桥管理区城桂路5号",
    "Avg_Cost": "",
    "Amap_URL": "https://surl.amap.com/a76pXLAO45P",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "65",
    "Restaurant_Name": "皇鴿餐廳",
    "Branch": "",
    "District": "五桂山鎮",
    "Category": "粵菜",
    "Highlight": "20年鑽研鴿子做法，紅燒、鹽焗、滷水鴿蛋一應俱全",
    "Description": "五桂山皇鴿餐廳成立於2004年，致力於鑽研鴿子的做法，一開始只是專門做湯鴿和鴿飯，2019年推出新口味，紅燒鴿、鹽焗味鴿和滷水鴿蛋，烹飪方法獨具特色，味道非常地道正宗。如今皇鴿在中山已有11家分店。",
    "Address": "中山市五桂山街道龍塘大山腳村龍塘工業大道138號",
    "Avg_Cost": "",
    "Amap_URL": "https://surl.amap.com/1EqrK7cV8fd",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "66",
    "Restaurant_Name": "林叔母食店(三乡总店)",
    "Branch": "",
    "District": "三鄉鎮",
    "Category": "粥麵小食",
    "Highlight": "百年老店三鄉無人不知，茶果瀨粉陪伴幾代人成長",
    "Description": "三鄉老店林叔母食店主打茶果、雞瀨、湯粉麵，每天凌晨開工，現做現賣。三鄉茶果系列有葉仔、芋頭糕、蘿蔔糕、白水餃、菜角、艾餅等，三鄉茶果傳統習俗已被列為中山市非物質文化遺產。",
    "Address": "中山市三乡镇平东村新下冲10巷6号之二",
    "Avg_Cost": "",
    "Amap_URL": "https://surl.amap.com/8eaWt3Y8cYG",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "67",
    "Restaurant_Name": "一煲鴿",
    "Branch": "",
    "District": "三鄉鎮",
    "Category": "粵菜",
    "Highlight": "2023年中山「舌尖上的中國」最具人氣口碑大賽第一名",
    "Description": "一煲鴿曾獲得2023年度中山市「舌尖上的中國」最具人氣口碑大賽第一名，乳鴿肉質鮮嫩多汁，每一口都能感受到肉質的細膩和鮮美，香氣四溢，不僅瀰漫在空氣中，更滲透進每個味蕾，讓人唇齒留香。",
    "Address": "中山市沙坦路与金涌大道交叉口东北80米",
    "Avg_Cost": "",
    "Amap_URL": "https://surl.amap.com/8glVbCO182oV",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "68",
    "Restaurant_Name": "中山溫泉中餐廳",
    "Branch": "",
    "District": "三鄉鎮",
    "Category": "粵菜",
    "Highlight": "溫泉旅遊區內的中山美食，乳鴿醬米蝦等菜品極致誘惑",
    "Description": "中山溫泉中餐廳不僅以溫泉聞名，更以獨特的中山美食吸引著四方賓客。在中山溫泉中餐廳，可以品嘗到乳鴿、醬米蝦等菜品，每一口都是對味蕾的極致誘惑，是遊覽中山溫泉旅遊區的絕佳用餐選擇。",
    "Address": "中山市南區街道三鄉鎮迎賓二路中山溫泉賓館內",
    "Avg_Cost": "",
    "Amap_URL": "https://surl.amap.com/1DXhGJUzgKI",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "69",
    "Restaurant_Name": "聚福寶合苑食府",
    "Branch": "",
    "District": "南頭鎮",
    "Category": "粵菜",
    "Highlight": "中山北部知名餐飲品牌，60 間豪華包房，適合家宴商宴",
    "Description": "中山北部的知名餐飲品牌，裝修優雅，提供多達 60 間豪華包房。主打地道粵式筵席菜式，適合家庭聚餐或商務宴請，是南頭鎮規模最大的正式餐廳之一。",
    "Address": "中山市南头镇升辉北路45号",
    "Avg_Cost": "110",
    "Amap_URL": "https://surl.amap.com/61TUdhgf75o",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "71",
    "Restaurant_Name": "冬城铁板烧(建业路店)",
    "Branch": "",
    "District": "南頭鎮",
    "Category": "粵菜",
    "Highlight": "建業路老字號粵菜館，傳統廣東菜式地道正宗",
    "Description": "位於建業路的粵菜館，是南頭鎮當地的老字號，多年來深受街坊喜愛。主打傳統廣東菜式，烹調手法地道正宗，是品嚐南頭本地風味的好去處。",
    "Address": "中山市南頭鎮建業路52號對面",
    "Avg_Cost": "50",
    "Amap_URL": "https://surl.amap.com/a49teKS13cYs",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "72",
    "Restaurant_Name": "滿好美食店",
    "Branch": "",
    "District": "南頭鎮",
    "Category": "家常菜",
    "Highlight": "13 年老字號，南頭人的集體回憶",
    "Description": "擁有 13 年歷史的老字號街坊食店，是許多南頭人的集體回憶。主打家常粵菜，食材新鮮，份量足，價格親民，烹調樸實無華卻充滿家的味道。",
    "Address": "中山市南头镇南头市场同乐中路34号",
    "Avg_Cost": "40",
    "Amap_URL": "https://surl.amap.com/a5LQaOC1w5i6",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "75",
    "Restaurant_Name": "日日照燒雞",
    "Branch": "",
    "District": "南頭鎮",
    "Category": "燒烤",
    "Highlight": "燒烤宵夜首選，燒雞香脆入味",
    "Description": "專門提供燒烤類美食的宵夜好去處，招牌燒雞外皮香脆、肉質鮮嫩入味，是南頭鎮街坊宵夜的熱門選擇，每逢夜晚人氣旺盛。",
    "Address": "中山市南头镇南和东路豪德巷花样年华东300米",
    "Avg_Cost": "40",
    "Amap_URL": "https://surl.amap.com/a9WYgD8yeN3",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "78",
    "Restaurant_Name": "正宗三仔土雞店",
    "Branch": "",
    "District": "南頭鎮",
    "Category": "家常菜",
    "Highlight": "土雞火鍋食材新鮮，正宗農家風味",
    "Description": "以土雞火鍋為主打，食材新鮮，選用正宗農家散養土雞，雞肉鮮甜結實，湯底清甜鮮美。是南頭鎮講究食材質素的街坊食店，深受注重健康飲食的食客喜愛。",
    "Address": "中山市南头镇同乐中路148号",
    "Avg_Cost": "65",
    "Amap_URL": "https://surl.amap.com/ad7OSngHcJ0",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "79",
    "Restaurant_Name": "Ameigo梅果·雲貴川bistro",
    "Branch": "",
    "District": "東區",
    "Category": "雲貴川菜",
    "Highlight": "大眾點評榜單上榜，雲貴川特色菜系，東區利和廣場",
    "Description": "中山東區利和廣場的雲貴川特色餐廳，融合雲南、貴州、四川菜系，以梅果風味著稱，環境時尚，深受年輕食客歡迎。",
    "Address": "中山市东区街道中山三路16号之一利和广场四层(410号商铺)",
    "Avg_Cost": "75",
    "Amap_URL": "https://surl.amap.com/7opF6DEZ8Es",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "80",
    "Restaurant_Name": "成大鴿皇桂園餐廳",
    "Branch": "",
    "District": "東區",
    "Category": "粵菜",
    "Highlight": "大眾點評榜單4.3分，中山最有名乳鴿專門餐廳之一",
    "Description": "中山東區著名乳鴿專門餐廳，以石岐乳鴿聞名，農莊環境舒適，招牌菜包括紅燒乳鴿、成大妙齡鴿、竹芋燜扇雞、天麻魚頭湯等，出品一流，深受本地人及遊客喜愛。",
    "Address": "中山市東區街道銀灣南路5號（奕翠園北門公交車站對面）",
    "Avg_Cost": "110",
    "Amap_URL": "https://surl.amap.com/9mDy54GTg8B",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "81",
    "Restaurant_Name": "Bos Park",
    "Branch": "",
    "District": "東區",
    "Category": "西式",
    "Highlight": "大眾點評榜單4.4高分，東區人氣西式餐廳",
    "Description": "中山東區高分西式餐廳，環境優美，提供多種西式料理，深受本地食客歡迎，是東區約會及聚餐的熱門選擇。",
    "Address": "中山市東區紫岭街道東路9號園區B棟一層",
    "Avg_Cost": "80",
    "Amap_URL": "https://surl.amap.com/5ezCjSOibB8",
    "Status": "",
    "Youtube": "https://youtube.com/shorts/7z1VMR1tYE0?si=QkbO4xkTj2ejBQj5",
    "sortbydate": ""
  },
  {
    "ID": "82",
    "Restaurant_Name": "岐余食堂·中華料理",
    "Branch": "",
    "District": "東區",
    "Category": "中華料理",
    "Highlight": "大眾點評榜單4.0分，富逸城特色中華料理",
    "Description": "位於中山東區富逸城的特色中華料理餐廳，菜式創意十足，環境舒適，是東區商圈的人氣食堂，適合家庭聚餐及商務宴請。",
    "Address": "中山市孙文东路686号富逸中心4层23卡",
    "Avg_Cost": "90",
    "Amap_URL": "https://surl.amap.com/7rQ09JgW8Eq",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "83",
    "Restaurant_Name": "拾嶼餐吧",
    "Branch": "",
    "District": "東區",
    "Category": "融合菜 Fusion",
    "Highlight": "大眾點評榜單4.0分，東區約會餐廳，首家花菲杯dirty",
    "Description": "中山東區時尚餐吧，主打創意料理與特色調飲，招牌86花菲杯dirty為中山首家，澳洲帶子燴飯廣受好評，環境精緻浪漫，是東區約會及聚餐的熱門打卡地。",
    "Address": "中山市东区长江路223号",
    "Avg_Cost": "120",
    "Amap_URL": "https://surl.amap.com/7spEytsz8sD",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "85",
    "Restaurant_Name": "食來久湘(天奕星河COCO City店)",
    "Branch": "",
    "District": "東區",
    "Category": "湘菜",
    "Highlight": "喜灣128美食街人氣湘菜館，招牌鮮炒黃牛肉",
    "Description": "位於中山東區喜灣128美食街的湘菜餐廳，主打鮮炒黃牛肉、剁椒鮮魚頭、高壓鍋粉蒸肉、久湘金廚豬手等湖南特色菜，食材新鮮，口味濃郁，飯點人氣爆棚。",
    "Address": "中山市東區東裕路128號（喜灣128美食街）",
    "Avg_Cost": "80",
    "Amap_URL": "https://surl.amap.com/1LXr2aOO9py",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "87",
    "Restaurant_Name": "尚赞泰式创意料理",
    "Branch": "",
    "District": "東區",
    "Category": "泰式料理",
    "Highlight": "喜灣128美食街泰式料理，招牌冬陰功海鮮湯",
    "Description": "位於中山東區喜灣128美食街的泰式特色餐廳，主打冬陰功海鮮湯、酸辣生蝦、黃金咖喱牛腩、泰式招牌咖喱蟹、招牌炭燒豬頸肉，口味正宗，深受喜愛東南亞料理的食客追捧。",
    "Address": "中山市东区东裕路128号109-110卡",
    "Avg_Cost": "80",
    "Amap_URL": "https://surl.amap.com/7xUBUqS1rabz",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "88",
    "Restaurant_Name": "禾熹鐵板刺身炭燒融合料理",
    "Branch": "",
    "District": "東區",
    "Category": "日式料理",
    "Highlight": "喜灣128美食街鐵板刺身炭燒融合料理，位上體驗",
    "Description": "位於中山東區喜灣128美食街的日式融合料理餐廳，主打位上鐵板料理，融合刺身、炭燒及鐵板烹調方式，食材新鮮，烹調精緻，提供獨特的日式用餐體驗。",
    "Address": "中山市東區東裕路128號115卡",
    "Avg_Cost": "135",
    "Amap_URL": "https://surl.amap.com/7yxZ5bQQ72b",
    "Status": "",
    "Youtube": "https://youtube.com/shorts/p_E4D1r66v0?si=ojkXQWPAVVKsRQnX",
    "sortbydate": ""
  },
  {
    "ID": "89",
    "Restaurant_Name": "美味園·脆肉鯇專賣店",
    "Branch": "",
    "District": "小欖鎮",
    "Category": "粵菜",
    "Highlight": "大眾點評必吃榜，小欖著名脆肉鯇專門店，人均RMB168",
    "Description": "中山小欖鎮著名脆肉鯇專賣店，庭園風格裝潢易打卡，脆肉鯇肉片新鮮清甜、皮脆肉質肥厚爽口有嚼勁，乳鴿脆皮鮮嫩多汁，二人套餐RMB168包含脆肉鯇、乳鴿、椒鹽魚骨等，性價比極高。",
    "Address": "中山市高沙社区明珠路2号之三",
    "Avg_Cost": "110",
    "Amap_URL": "https://surl.amap.com/8DWcnnIh8u3",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "90",
    "Restaurant_Name": "東升(國宴)大酒樓",
    "Branch": "",
    "District": "東升鎮",
    "Category": "粵菜",
    "Highlight": "葵興大道地標酒樓，招牌冰鎮鮑魚及蒜蓉大明蝦",
    "Description": "位於小欖鎮葵興大道的大型粵菜酒樓，裝潢氣派，設有多個宴會廳，適合家庭聚餐及商務宴請。招牌菜包括冰鎮鮑魚、芝士焗大花龍蝦、濃湯雞煲翅、紅燒石岐乳鴿及蒜蓉大明蝦，早市點心亦廣受好評。",
    "Address": "中山市葵兴大道57号",
    "Avg_Cost": "90",
    "Amap_URL": "https://surl.amap.com/bjDu042169HL",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "91",
    "Restaurant_Name": "港升魚師傅",
    "Branch": "",
    "District": "小欖鎮",
    "Category": "粵菜",
    "Highlight": "小欖脆肉鯇創意菜名店，鮑汁脆鯇嘴獨家招牌",
    "Description": "小欖鎮深中通道開通後大受遊客追捧的脆肉鯇創意料理店，以創新手法演繹傳統食材。招牌菜包括鮑汁脆肉鯇嘴、黃金萬兩脆鯇腩及咖喱煮脆鯇片，將脆肉鯇做出多種風味，深受食客好評。",
    "Address": "中山市小欖鎮同樂大街一路107號第13卡",
    "Avg_Cost": "110",
    "Amap_URL": "https://surl.amap.com/b4ItCRkudym",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "92",
    "Restaurant_Name": "九洲盛宴酒樓",
    "Branch": "",
    "District": "小欖鎮",
    "Category": "粵菜",
    "Highlight": "以石硖龍眼入饌的特色宴席，龍眼宴聞名",
    "Description": "小欖鎮九洲花園旁的特色粵菜酒樓，以當地出產的石硖龍眼為主題食材，創製獨特龍眼宴。招牌菜包括杏香龍眼酥、蘭花蚌炒龍珠等，將龍眼融入多道菜式，是品嚐小欖地道風味的好去處。",
    "Address": "中山市小欖鎮育才路八街（九洲花園西）",
    "Avg_Cost": "135",
    "Amap_URL": "https://surl.amap.com/b3iBfGW1z9uj",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "93",
    "Restaurant_Name": "小欖公飯店",
    "Branch": "",
    "District": "小欖鎮",
    "Category": "粵菜",
    "Highlight": "小欖老字號，撈起脆肉鯇及菊花刺身地道名菜",
    "Description": "小欖鎮的傳統老字號粵菜館，以地道小欖風味聞名。招牌菜包括撈起脆肉鯇、菊花刺身、黃皮醬燒雞及小欖炸魚球，每逢菊花節期間更有特色菊花宴，是感受小欖飲食文化的必訪之地。",
    "Address": "中山市小榄镇北区村a区97号",
    "Avg_Cost": "60",
    "Amap_URL": "https://surl.amap.com/b3n3lhg1146F",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "94",
    "Restaurant_Name": "雀鳥軒海鮮漁村",
    "Branch": "",
    "District": "沙溪鎮",
    "Category": "海鮮酒樓",
    "Highlight": "高德榜單4.64分，紅燒乳鴿皮脆肉嫩",
    "Description": "位於中山市的特色海鮮漁村餐廳，以新鮮海鮮及地道粵菜聞名，環境清幽。紅燒乳鴿皮脆肉嫩，是食客必點招牌菜，各式海鮮亦新鮮美味，深受本地食客及遊客喜愛。",
    "Address": "中山市沙溪鎮隆都路61號",
    "Avg_Cost": "90",
    "Amap_URL": "https://surl.amap.com/9EFZaH017aIx",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "96",
    "Restaurant_Name": "鈺緣軒餐飲店",
    "Branch": "",
    "District": "小欖鎮",
    "Category": "粵菜",
    "Highlight": "小欖鎮績東社區地道粵菜小館",
    "Description": "位於小欖鎮績東一社區的地道粵菜小館，提供傳統廣東家常菜式，食材新鮮，烹調用心，是附近居民日常用餐的熟悉選擇。",
    "Address": "中山市小欖鎮績東一社區興達路9號地舖卡2室",
    "Avg_Cost": "55",
    "Amap_URL": "https://surl.amap.com/b6JoPLYG5z6",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "97",
    "Restaurant_Name": "海洲九记云吞",
    "Branch": "",
    "District": "古鎮鎮",
    "Category": "粵菜",
    "Highlight": "傳承三代 50 年，皮薄餡靚湯鮮的古鎮雲吞老字號",
    "Description": "古鎮鎮最具代表性的雲吞老字號，傳承三代人超過 50 年。大骨熬製玉露清湯，雲吞皮薄如紙，餡料鮮美，是古鎮人從小吃到大的街頭美食。",
    "Address": "中山市乐丰花园金碧轩北门旁",
    "Avg_Cost": "35",
    "Amap_URL": "https://surl.amap.com/8Te8jWy76fx",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "98",
    "Restaurant_Name": "外家鸽(古镇国贸店)",
    "Branch": "國貿店",
    "District": "古鎮鎮",
    "Category": "粵菜",
    "Highlight": "藥膳鴿、鹽焗鴿、脆皮乳鴿，古鎮人氣鴿肉專門店",
    "Description": "古鎮鎮人氣鴿肉餐廳，主打藥膳鴿、鹽焗鴿、脆皮乳鴿等多種烹調方式，另有榴蓮餅、臘味煲仔飯等特色菜式，環境舒適，深受本地食客喜愛。",
    "Address": "中山市永利国贸广场",
    "Avg_Cost": "75",
    "Amap_URL": "https://surl.amap.com/8VlKVhozaUw",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "99",
    "Restaurant_Name": "一品魚羊",
    "Branch": "古鎮分店",
    "District": "古鎮鎮",
    "Category": "私房菜",
    "Highlight": "蟹黃蒸蛋、蒸鱈魚、蒜蓉蒸生蠔，古鎮私房菜精選",
    "Description": "古鎮鎮頗受好評的私房菜餐廳，主打新鮮海鮮與精緻粵菜，蟹黃蒸蛋、蒸鱈魚、蒜蓉蒸生蠔、紫蘇焗排骨、脆肉鯇、刺身拼盤均為招牌菜式。",
    "Address": "中山市勤政一路与赛龙路交叉口北180米",
    "Avg_Cost": "110",
    "Amap_URL": "https://surl.amap.com/8WYs02un3rv",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "100",
    "Restaurant_Name": "海洲鱼饼(曹步市场店)",
    "Branch": "曹步市場店",
    "District": "古鎮鎮",
    "Category": "粵菜",
    "Highlight": "古鎮非遺魚餅，皮香肉滑金黃純淨，80年老字號",
    "Description": "海洲魚餅是古鎮最出名的傳統小食之一，甘香不俗，爽而韌，嫩滑而不散，隔夜無餿味。北海村榕樹頭魚餅店已開張 80 多年，前後四代人經營，2003 年申請商標品牌。",
    "Address": "中山市古镇镇古镇曹步市场西安上街4巷",
    "Avg_Cost": "25",
    "Amap_URL": "https://surl.amap.com/8YukY8Wv7WH",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "102",
    "Restaurant_Name": "一品盛宴大酒楼",
    "Branch": "",
    "District": "橫欄鎮",
    "Category": "粵菜",
    "Highlight": "堂啫澳洲牛仔骨、堂啫大龍趸，橫欄鎮人氣海鮮酒樓",
    "Description": "橫欄鎮頗具人氣的大型海鮮酒樓，以堂啫系列菜式見長，澳洲牛仔骨和大龍趸是招牌，食材新鮮，烹調火候到位，深受本地食客及周邊居民喜愛。",
    "Address": "中山市顺兴南路39号",
    "Avg_Cost": "90",
    "Amap_URL": "https://surl.amap.com/asjoPfY148Pd",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "104",
    "Restaurant_Name": "順德私廚",
    "Branch": "",
    "District": "橫欄鎮",
    "Category": "順德菜",
    "Highlight": "招牌棟企雞、筲箕魚，橫欄鎮正宗順德私廚",
    "Description": "橫欄鎮的順德私廚，以傳統順德菜為主打，棟企雞和筲箕魚是招牌菜式，食材講究，烹調手法傳統，是品嚐正宗順德風味的好去處。",
    "Address": "中山市橫欄鎮新豐村穗平街88號首層",
    "Avg_Cost": "90",
    "Amap_URL": "https://surl.amap.com/avgCNFUkeiX",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "105",
    "Restaurant_Name": "梁山酒家",
    "Branch": "",
    "District": "橫欄鎮",
    "Category": "粵菜",
    "Highlight": "海鱸刺身、海鮮大菜，橫欄鎮老牌酒家",
    "Description": "橫欄鎮老牌酒家，以新鮮海鱸刺身和各式海鮮大菜著稱，環境寬敞，適合家庭聚餐及商務宴請，是橫欄鎮居民信賴的飲食選擇。",
    "Address": "中山市橫欄鎮長安北路210號首層之一、二樓之一",
    "Avg_Cost": "90",
    "Amap_URL": "https://surl.amap.com/awT6rY6G5aI",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "107",
    "Restaurant_Name": "小木屋農莊",
    "Branch": "",
    "District": "阜沙鎮",
    "Category": "農家菜",
    "Highlight": "脆肉羅非魚，田園風光中的農家美食體驗",
    "Description": "阜沙鎮田園風光中的農莊餐廳，主打脆肉羅非魚及各式農家菜，環境清幽，食材來自自家農場，是親子家庭及週末休閒的熱門選擇。大眾點評評分 4.5。",
    "Address": "中山市智城汇谷产业园北侧320米",
    "Avg_Cost": "65",
    "Amap_URL": "https://surl.amap.com/aLvimFQq9Bw",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "108",
    "Restaurant_Name": "河宴食府",
    "Branch": "阜沙店",
    "District": "阜沙鎮",
    "Category": "粵菜",
    "Highlight": "阜沙河鮮料理，蘭蒂斯酒店內精緻粵菜",
    "Description": "位於阜沙鎮蘭蒂斯酒店內的精緻粵菜餐廳，主打新鮮河鮮料理，食材來自珠三角水域，烹調精緻，環境優雅，適合商務宴請及家庭聚餐。",
    "Address": "中山市阜沙镇上南村锦绣路31号首层四卡",
    "Avg_Cost": "90",
    "Amap_URL": "https://surl.amap.com/aKnna9I1mdrA",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "109",
    "Restaurant_Name": "自然豐",
    "Branch": "",
    "District": "阜沙鎮",
    "Category": "農家菜",
    "Highlight": "特色花果宴，以花入饌的創意農莊菜",
    "Description": "阜沙鎮特色農莊餐廳，以花果入饌為特色，推出別具一格的花果宴，食材天然健康，環境清新，是阜沙鎮最具特色的農家菜體驗之一。",
    "Address": "中山市阜沙鎮永紅街6號阜沙里",
    "Avg_Cost": "75",
    "Amap_URL": "https://surl.amap.com/aMehNwuegYv",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "110",
    "Restaurant_Name": "黃牛仔酒樓",
    "Branch": "",
    "District": "民眾鎮",
    "Category": "粵菜",
    "Highlight": "廣式早茶、粵菜，民眾鎮老牌酒樓",
    "Description": "民眾鎮老牌粵菜酒樓，主打廣式早茶及傳統粵菜，是民眾鎮居民日常飲茶、家庭聚餐的熟悉選擇，環境寬敞，菜品實惠。",
    "Address": "中山市民眾大道106號",
    "Avg_Cost": "65",
    "Amap_URL": "https://surl.amap.com/90fKtFoxehL",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "111",
    "Restaurant_Name": "松濤居·荔枝柴燒鵝",
    "Branch": "三墩總店",
    "District": "民眾鎮",
    "Category": "粵菜",
    "Highlight": "三墩燜鵝、荔枝柴燒鵝，民眾鎮水鄉名物",
    "Description": "民眾鎮三墩村的燒鵝名店，以荔枝柴燒鵝和三墩燜鵝聞名，鵝皮脆、肉嫩、汁鮮，是民眾鎮水鄉美食的代表。油鹽飯、燒鵝、燜鵝、鵝雜均為必點菜式。",
    "Address": "中山市民众镇三墩行政村三益路173号之1号",
    "Avg_Cost": "80",
    "Amap_URL": "https://surl.amap.com/937CYzMy9Jm",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "112",
    "Restaurant_Name": "秋記食店",
    "Branch": "",
    "District": "民眾鎮",
    "Category": "粵菜",
    "Highlight": "老牌燜鵝食店，傳統農家做法代代相傳",
    "Description": "民眾鎮三墩村的老牌燜鵝食店，以傳統農家做法烹製燜鵝，火候到位，鵝肉入味，是民眾鎮最具代表性的地道農家菜之一。",
    "Address": "中山市三墩行政村正涌上街95號",
    "Avg_Cost": "65",
    "Amap_URL": "https://surl.amap.com/90KGQgWj5iE",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "113",
    "Restaurant_Name": "翔雄農莊",
    "Branch": "",
    "District": "民眾鎮",
    "Category": "農家菜",
    "Highlight": "以花入饌的花樣鮮味，民眾鎮特色農莊體驗",
    "Description": "民眾鎮特色農莊餐廳，以花入饌，推出別具一格的花樣鮮味菜式，食材健康天然，環境田園清新，是民眾鎮最具特色的農家菜體驗場所。",
    "Address": "中山市民眾街道接源村眾安大道1號泰豐鳳凰源右側1卡",
    "Avg_Cost": "75",
    "Amap_URL": "https://surl.amap.com/93exnrYY2zI",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "114",
    "Restaurant_Name": "金記大酒樓",
    "Branch": "",
    "District": "火炬開發區",
    "Category": "粵菜",
    "Highlight": "皇牌水魚羹獲粵菜師傅特金獎，火炬老字號 1982 年創立",
    "Description": "始創於 1982 年的火炬開發區老字號酒樓，主打特色粵菜，招牌菜「皇牌水魚羹」曾榮獲火炬開發區「粵菜師傅」特金獎，是火炬區最具代表性的傳統粵菜酒樓。",
    "Address": "中山市中山东区街道孙文东路833号",
    "Avg_Cost": "90",
    "Amap_URL": "https://surl.amap.com/8O8QTfYnbtW",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "115",
    "Restaurant_Name": "海然漁邨",
    "Branch": "",
    "District": "火炬開發區",
    "Category": "海鮮酒樓",
    "Highlight": "姜蔥炒龍蝦、清蒸龍趸、皮皮蝦，火炬區人氣海鮮村",
    "Description": "火炬開發區人氣海鮮餐廳，以新鮮活海鮮見長，姜蔥炒龍蝦肉質 Q 彈，皮皮蝦膏黃肉肥酥香入味，清蒸龍趸滑嫩爽口鮮甜多汁，是海鮮愛好者的必訪之地。",
    "Address": "中山市中山市开发区东阳北路2号",
    "Avg_Cost": "110",
    "Amap_URL": "https://surl.amap.com/8Qelk0i1nb72",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "116",
    "Restaurant_Name": "西关楼(中山富逸城店)",
    "Branch": "火炬店",
    "District": "火炬開發區",
    "Category": "粵菜",
    "Highlight": "西關蝦餃皇、小黃鴨蛋撻、鮑魚燒賣，精緻嶺南點心",
    "Description": "西關樓·嶺南茶樓在中山設有多家分店，火炬店主打精緻粵式點心，西關蝦餃皇、豉汁蒸排骨、脆皮紅米腸等傳統點心外，還有小黃鴨泡泡浴蛋撻、蘋果造型平安包等創意點心，深受食客喜愛。",
    "Address": "中山市火炬开发区联富社区孙文东路686号二层J2-01A",
    "Avg_Cost": "80",
    "Amap_URL": "https://surl.amap.com/80eipN81qaJW",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "117",
    "Restaurant_Name": "醇品大酒樓",
    "Branch": "",
    "District": "火炬開發區",
    "Category": "粵菜",
    "Highlight": "鮮嫩白切雞、魚羊鮮煲，嶺南文化體驗酒樓",
    "Description": "火炬開發區精緻粵菜酒樓，以精緻烹飪手法呈現粵菜傳統風味，鮮嫩白切雞、滋補魚羊鮮煲及各類精心炮製的特色茶點均為招牌，是一次深度的嶺南文化飲食體驗。",
    "Address": "中山市東鎮東一路23號太陽城5樓5F001卡",
    "Avg_Cost": "90",
    "Amap_URL": "https://surl.amap.com/8QFoQfodeMF",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "119",
    "Restaurant_Name": "香山府酒樓",
    "Branch": "",
    "District": "馬鞍島",
    "Category": "粵菜",
    "Highlight": "香山炒飯、芝士和牛蛋撻，翠亨新區精緻粵菜",
    "Description": "位於馬鞍島翠亨新區的精緻粵菜酒樓，香山炒飯和芝士和牛蛋撻是招牌菜式，融合傳統粵菜與創新元素，環境優雅，是翠亨新區的高品質飲食選擇。",
    "Address": "中山市翠亨新區和信路18號翠亨大廈商業中心3樓",
    "Avg_Cost": "90",
    "Amap_URL": "https://surl.amap.com/axeIcu6F5lx",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "120",
    "Restaurant_Name": "野Wild洲際廚房",
    "Branch": "",
    "District": "馬鞍島",
    "Category": "私房菜",
    "Highlight": "馬鞍島沙律、金槍魚塔塔、自家種青檸蒸魚，翠亨新區創意料理",
    "Description": "馬鞍島翠亨新區的創意洲際廚房，以新鮮食材和創意烹調見長，馬鞍島沙律、金槍魚塔塔、自家種青檸蒸魚均為招牌，是翠亨新區最具個性的餐廳之一。",
    "Address": "中山市翠亨新区中兴懿港汇16栋二楼",
    "Avg_Cost": "90",
    "Amap_URL": "https://surl.amap.com/azFSZUmV1X9",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "121",
    "Restaurant_Name": "翠亨牛鮮府",
    "Branch": "",
    "District": "馬鞍島",
    "Category": "火鍋",
    "Highlight": "牛肉火鍋、海鮮烤盤，馬鞍島翠亨新區特色火鍋",
    "Description": "馬鞍島翠亨新區的特色牛肉火鍋與海鮮烤盤餐廳，食材新鮮，牛肉品質上乘，是翠亨新區居民和遊客的熱門聚餐選擇。",
    "Address": "中山市翠亨新區馬鞍島未來大道30號研發車間第一層11-12卡",
    "Avg_Cost": "100",
    "Amap_URL": "https://surl.amap.com/aAcxWdkffKq",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "122",
    "Restaurant_Name": "鳳凰城海鮮酒樓",
    "Branch": "",
    "District": "大涌鎮",
    "Category": "粵菜",
    "Highlight": "隔水蒸藥膳鴿、德國咸豬手，大涌隆都菜名店",
    "Description": "大涌鎮隆都菜代表性餐廳，主打特色火鍋、隔水蒸藥膳鴿、德國咸豬手等菜式，融合傳統隆都菜與創新元素，是大涌鎮最受歡迎的聚餐場所之一。",
    "Address": "中山市南文市场南兴东路店4号门旁",
    "Avg_Cost": "75",
    "Amap_URL": "https://surl.amap.com/8q47xWy1seQn",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "123",
    "Restaurant_Name": "安西酒樓",
    "Branch": "",
    "District": "大涌鎮",
    "Category": "粵菜",
    "Highlight": "子姜燜鴨、鮑汁扣花菇、冰鎮咕嚕肉，大涌隆都三寶",
    "Description": "大涌鎮安堂市場的老牌酒樓，主打傳統隆都菜，子姜燜鴨、鮑汁扣花菇、冰鎮咕嚕肉是招牌菜式，隆都菜以白切雞、扣肉、子姜燜鴨三寶著稱，食材新鮮，烹調地道。",
    "Address": "中山市大涌镇安堂市场2层",
    "Avg_Cost": "65",
    "Amap_URL": "https://surl.amap.com/8sGeoUqt1Nt",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "124",
    "Restaurant_Name": "昇輝海鮮酒樓",
    "Branch": "",
    "District": "大涌鎮",
    "Category": "海鮮酒樓",
    "Highlight": "大涌鎮安堂九龍門牌坊旁，新鮮海鮮大菜",
    "Description": "大涌鎮安堂九龍門牌坊旁的海鮮酒樓，提供新鮮海鮮及傳統粵菜，環境寬敞，是大涌鎮居民家庭聚餐及宴請賓客的熱門選擇。",
    "Address": "中山市中新路与仁桂路交叉口西北40米",
    "Avg_Cost": "80",
    "Amap_URL": "https://surl.amap.com/8tp8NAe113Hb",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "125",
    "Restaurant_Name": "勵豪商務酒店真味廚房",
    "Branch": "",
    "District": "大涌鎮",
    "Category": "粵菜",
    "Highlight": "脆皮燒腩仔、香茅焗桂蝦、土茯苓煲鴿子",
    "Description": "大涌鎮勵豪商務酒店內的精緻粵菜廚房，主打脆皮燒腩仔、香茅焗桂蝦、土茯苓煲鴿子等特色菜式，食材講究，烹調精緻，是大涌鎮商務宴請的優質選擇。",
    "Address": "中山市大涌鎮旗山路1號",
    "Avg_Cost": "90",
    "Amap_URL": "https://surl.amap.com/8tRnKnoQbp8",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "126",
    "Restaurant_Name": "中山四海酒楼",
    "Branch": "",
    "District": "板芙鎮",
    "Category": "粵菜",
    "Highlight": "首創木姜子乳鴿、馬友魚蛋撻，板芙鎮地標酒樓",
    "Description": "板芙鎮地標性粵菜酒樓，以首創木姜子乳鴿聞名，馬友魚蛋撻和香芒豬頸柳同樣是招牌菜式，是板芙鎮最具代表性的餐廳之一。",
    "Address": "中山市板芙镇商业街68号3至5层",
    "Avg_Cost": "80",
    "Amap_URL": "https://surl.amap.com/aDTtp0K1k9Wt",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "127",
    "Restaurant_Name": "千江魚酒樓",
    "Branch": "",
    "District": "板芙鎮",
    "Category": "粵菜",
    "Highlight": "拍薑蒸三泥、荔枝柴燒鵝、大廚炒飯，板芙鎮人氣酒樓",
    "Description": "板芙鎮人氣酒樓，融合粵菜、海鮮、川菜、湘菜，拍薑蒸三泥、荔枝柴燒鵝、大廚炒飯是招牌菜式，食材新鮮，菜式多樣，適合各種口味的食客。",
    "Address": "中山市板芙鎮濱江二路38號（聚豐米業側）",
    "Avg_Cost": "80",
    "Amap_URL": "https://surl.amap.com/aCAwGLg1ufkr",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "128",
    "Restaurant_Name": "良記私廚",
    "Branch": "",
    "District": "板芙鎮",
    "Category": "私房菜",
    "Highlight": "黑蒜老家酒蒸三層肉、西江龍利，板芙鎮西江河鮮私廚",
    "Description": "板芙鎮以西江河鮮和創新融合菜為主打的私廚，黑蒜老家酒蒸三層肉、鹽焗水鴨、西江龍利是招牌菜式，食材來自西江水域，新鮮美味，是板芙鎮最具特色的私廚之一。",
    "Address": "中山市工业大道与广珠公路辅路交叉口南40米",
    "Avg_Cost": "90",
    "Amap_URL": "https://surl.amap.com/aE7NfPY1AgPd",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "130",
    "Restaurant_Name": "御景灣海鮮酒樓",
    "Branch": "",
    "District": "神灣鎮",
    "Category": "海鮮酒樓",
    "Highlight": "神灣鎮主打粵菜海鮮，怡景灣商業樓地標酒樓",
    "Description": "神灣鎮怡景灣商業樓的地標海鮮酒樓，以粵菜和海鮮為主，食材新鮮，是神灣鎮居民家庭聚餐及宴請賓客的首選場所。",
    "Address": "中山市神湾镇怡景湾商业1幢125卡一层",
    "Avg_Cost": "80",
    "Amap_URL": "https://surl.amap.com/aNSB9Lsu3Wb",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "131",
    "Restaurant_Name": "广隆饭店",
    "Branch": "",
    "District": "神灣鎮",
    "Category": "粵菜",
    "Highlight": "燒鵝、生蠔、湛江豬手，神灣鎮竹排村地道粵菜",
    "Description": "神灣鎮竹排村的地道粵菜飯店，燒鵝、生蠔、湛江豬手、燒味拼盤、陳皮骨、一桶雞均為招牌菜式，烹調傳統，食材新鮮，是神灣鎮最具代表性的地道餐廳之一。",
    "Address": "中山市神灣鎮竹排路段（近斗門大橋）",
    "Avg_Cost": "75",
    "Amap_URL": "https://surl.amap.com/aOoxCwG1e0G9",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "132",
    "Restaurant_Name": "賣魚添飯店",
    "Branch": "",
    "District": "神灣鎮",
    "Category": "粵菜",
    "Highlight": "用心挑選健康食材，神灣鎮新市場旁地道小館",
    "Description": "神灣鎮新市場旁的地道粵菜小館，以用心挑選健康食材、傳遞愛的味道為理念，提供新鮮地道的神灣本土菜式，是神灣鎮居民日常用餐的熟悉選擇。",
    "Address": "中山市神灣鎮神灣新市場側面",
    "Avg_Cost": "55",
    "Amap_URL": "https://surl.amap.com/aOsL1Bo4ghA",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "133",
    "Restaurant_Name": "孖宝庄园",
    "Branch": "",
    "District": "南頭鎮",
    "Category": "粵菜",
    "Highlight": "珠三角最大園林食府之一，佔地90畝，荔枝木燒鵝馳名",
    "Description": "孖宝庄园由1995年開業，是珠三角地區面積最大的園林食府之一，佔地90畝（逾5萬平方米），停車位超過400個。2024年完成升級改造重新開業，新中式建築風格融合園林景觀設計，環境豪華優美。招牌菜包括荔枝木燒鵝、石鍋蒜香焗生蚝、干燒大羅氏蝦、涼拌魚皮等，是南頭鎮最具代表性的高端粵菜食府，適合家宴、商務宴請及大型聚會。",
    "Address": "廣東省中山市南頭鎮南和東路693號",
    "Avg_Cost": "100",
    "Amap_URL": "https://surl.amap.com/a7K6U2O147Pn",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "134",
    "Restaurant_Name": "韶味軒月婆雞瀨",
    "Branch": "",
    "District": "三鄉鎮",
    "Category": "粉麵米線",
    "Highlight": "正宗三鄉月婆雞瀨，鮮甜雞湯底配爽滑瀨粉，街坊老字號",
    "Description": "韶味軒是三鄉鎮最具代表性的月婆雞瀨專門店，以正宗三鄉月婆雞湯底配搭爽滑瀨粉聞名，深受本地街坊及港澳食客喜愛。招牌月婆雞瀨湯底鮮甜，雞肉嫩滑，另有豬肚雞瀨、枸杞葉豬雜瀨粉等特色選擇，全日營業，早餐至宵夜均可光顧。",
    "Address": "廣東省中山市三鄉鎮金涌大道雅居樂花園H29-34號鋪",
    "Avg_Cost": "25",
    "Amap_URL": "https://surl.amap.com/8ilbAYaK4UE",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "135",
    "Restaurant_Name": "60+ All Day Breakfast",
    "Branch": "",
    "District": "三鄉鎮",
    "Category": "西式",
    "Highlight": "三鄉雅居樂人氣全日早餐，港式西式兼備，環境舒適",
    "Description": "60+ All Day Breakfast 位於三鄉鎮雅居樂新城，是深受港人及本地居民喜愛的全日早餐餐廳。主打港式西式早餐，菜式豐富，環境輕鬆舒適，老闆熱情健談，是三鄉雅居樂社區的人氣打卡食店。",
    "Address": "中山市三乡镇景观大道雅贤街1号雅居乐新城十期1区28卡首层",
    "Avg_Cost": "55",
    "Amap_URL": "https://surl.amap.com/8jOayP8Sbz0",
    "Status": "",
    "Youtube": "https://youtube.com/shorts/KExW4E_YSVk?si=oFPbvF6e24HsszZk",
    "sortbydate": ""
  },
  {
    "ID": "136",
    "Restaurant_Name": "佬少爺果木窯雞研究所",
    "Branch": "",
    "District": "南朗鎮",
    "Category": "農家菜",
    "Highlight": "4.8高分！果木窯雞皮脆肉嫩，崖口食街海邊環境優美",
    "Description": "位於崖口食街沙頭涌海邊的特色農莊菜館，以果木窯雞聞名，窯雞皮脆肉嫩、香氣四溢。環境優美，停車方便，菜品豐富，價格划算，不到300元即可享用5-6人套餐，包含招牌果木窯雞及多款特色菜式，是崖口打卡花海後的熱門飯堂。",
    "Address": "中山市南朗街道崖口村沙頭涌邊（沙頭涌派出所西南500米）",
    "Avg_Cost": "88",
    "Amap_URL": "https://surl.amap.com/aj0mV7ku97S",
    "Status": "",
    "Youtube": "https://youtube.com/shorts/9W9LM2IYX9Y?si=KxTdS8kimRPWnGm3",
    "sortbydate": ""
  },
  {
    "ID": "137",
    "Restaurant_Name": "棠記海鮮餐廳",
    "Branch": "崖口店",
    "District": "南朗鎮",
    "Category": "海鮮酒樓",
    "Highlight": "2008年開業老字號，鹹淡水海鮮新鮮豐富，原只蒸奄仔蟹鮮美無比",
    "Description": "自2008年開業，位於崖口沙頭涌海邊，地處珠江口岸，自然風光優美。餐廳堅持誠信經營，野生海鮮品種新鮮且豐富多樣，以鹹淡水海鮮為主，原只蒸奄仔蟹鮮美無比，白蝦也很甜，紅樹林就在腳底，景色一流。",
    "Address": "中山市南朗街道崖口沙頭涌海邊崖口集益廟附近",
    "Avg_Cost": "100",
    "Amap_URL": "https://surl.amap.com/ak4Wqqm1l4Dl",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "138",
    "Restaurant_Name": "中山市红树林海鲜餐厅",
    "Branch": "",
    "District": "南朗鎮",
    "Category": "海鮮酒樓",
    "Highlight": "紅樹林海邊大排檔，蔥汁米酒燜風鱔是人氣招牌菜",
    "Description": "環境優美的崖口紅樹林海邊大排檔，食材新鮮，人氣菜品蔥汁米酒燜風鱔，用蔥汁米酒激發出風鱔的鮮美，最後灑上橘葉絲，別有一番風味。帶膏皮皮蝦、膏蟹、招牌手拆雞、炒螺子均為必點菜式。",
    "Address": "中山市南朗街道崖口村沙頭涌海邊（崖口集益廟附近）",
    "Avg_Cost": "80",
    "Amap_URL": "https://surl.amap.com/alEBWFIb6rM",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "139",
    "Restaurant_Name": "廣亮煲仔飯",
    "Branch": "鄉墟店（第一家）",
    "District": "南朗鎮",
    "Category": "煲仔飯",
    "Highlight": "崖口本地五星米煲仔飯，50+食材任選，人氣排隊名店",
    "Description": "崖口村著名煲仔飯店，精選崖口稻田收割的五星米和象牙米，每年日曬、脫皮、封存，米飯粒粒分明又飽滿。提供50多種食材包括肉類、乾/濕海鮮類任意挑選，食客自選食材搭配出獨一無二的口味，上座率高，是崖口最具代表性的地道小食。",
    "Address": "中山市南朗街道崖口村沙頭涌路段（崖口食街）",
    "Avg_Cost": "30",
    "Amap_URL": "",
    "Status": "X",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "140",
    "Restaurant_Name": "细松云吞店",
    "Branch": "中堡店",
    "District": "南朗鎮",
    "Category": "粥麵小食",
    "Highlight": "20多年歷史，開在崖口村祠堂裡的雲吞老店，皮薄肉嫩",
    "Description": "有著20多年歷史的崖口雲吞老店，開在崖口村祠堂裡，是崖口人的常駐之地。雲吞皮薄肉嫩，一口下去滿滿的幸福感，崖口雲吞聞名珠三角，是來崖口必食的地道小吃。",
    "Address": "中山市崖口中堡可庵谭公祠旁",
    "Avg_Cost": "15",
    "Amap_URL": "https://surl.amap.com/amROqymdcIB",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "141",
    "Restaurant_Name": "向雲端咖啡",
    "Branch": "",
    "District": "南朗鎮",
    "Category": "咖啡 Chill 地方",
    "Highlight": "無敵稻田景觀咖啡廳，宮崎駿動畫風格，打卡熱點",
    "Description": "崖口村稻田邊的田園咖啡廳，落地窗外是一片綠油油的稻田，陽光灑在金黃色稻浪上，搭配純白色簡約咖啡屋，完全是宮崎駿動畫裡走出來的場景。是崖口村最具代表性的網紅咖啡店，週末人氣極旺，建議工作日前往。",
    "Address": "中山市南朗街道崖口村下田林公園1號",
    "Avg_Cost": "40",
    "Amap_URL": "https://surl.amap.com/anqwVhU1s5px",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "142",
    "Restaurant_Name": "W Coffee",
    "Branch": "",
    "District": "南朗鎮",
    "Category": "咖啡 Chill 地方",
    "Highlight": "崖口陸家村田園秘境咖啡，木質小屋配稻田宛如動畫場景",
    "Description": "藏在崖口陸家村樹蔭深處的田園秘境咖啡店，眼前整片綠油油的稻田配上木質屋，簡直像從宮崎駿動畫裡跑出來的場景，瞬間治癒打工疲勞。旁邊就是傳統市集，喝完咖啡還能去品嚐崖口雲吞、蘿蔔糕，感受最地道的中山煙火氣。",
    "Address": "中山市南朗街道崖口陸家村敦和路18號",
    "Avg_Cost": "40",
    "Amap_URL": "https://surl.amap.com/apI01OWm91T",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "143",
    "Restaurant_Name": "魚鄉茶樓",
    "Branch": "星寶店",
    "District": "沙溪鎮",
    "Category": "粤菜酒樓",
    "Highlight": "沙溪打卡人氣榜第1名，22年名店，吊水脆肉鯇大頭魚",
    "Description": "中山地標美食，22年老字號名店。主打吊水脆肉鯇、大頭魚，全部山泉水養殖，魚肉清甜爽滑。一魚多味，魚頭砂鍋、椒鹽魚骨、魚腸煎蛋各具特色。大眾點評沙溪鎮美食打卡人氣榜第1名，廣式早茶點心亦出色，煎堆巨大酥脆。",
    "Address": "中山市星宝路2号星宝明珠花园3期25幢160",
    "Avg_Cost": "75",
    "Amap_URL": "https://surl.amap.com/9xtJq5UigEV",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "144",
    "Restaurant_Name": "正丰鱼",
    "Branch": "",
    "District": "東區",
    "Category": "粵菜",
    "Highlight": "中山十大名優食材Farm-to-table，山泉水養殖，長江水世界旁，可容納800人",
    "Description": "中山十大名優食材Farm-to-table，從養魚到煮魚保證最靚品質。農場山泉水清水邊爐，只有劏魚師傅的店鋪，可容納800人同時就餐。主打脆肉鯇、大頭魚、草魚等中山特色淡水魚，新鮮現劏現煮。2019年獲評中山十大名優食材，2023年入選「魚躍中山」品牌榜。",
    "Address": "中山市東區街道怡景路6號（長江水世界旁）",
    "Avg_Cost": "80",
    "Amap_URL": "https://surl.amap.com/azurTgigbdb",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "145",
    "Restaurant_Name": "雀鳥軒海鮮漁村",
    "Branch": "",
    "District": "沙溪鎮",
    "Category": "海鮮酒樓",
    "Highlight": "沙溪老牌海鮮漁村，沙溪扣肉、煎焗魚嘴馳名",
    "Description": "沙溪鎮老牌海鮮漁村，環境寬敞，以地道沙溪風味見稱。招牌菜沙溪扣肉肥而不膩，煎焗魚嘴鮮嫩入味，醬燒排骨香濃可口。新鮮海鮮即點即煮，深受本地食客歡迎。",
    "Address": "中山市沙溪镇隆都路61号",
    "Avg_Cost": "60",
    "Amap_URL": "https://surl.amap.com/9EFZaH017aIx",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "146",
    "Restaurant_Name": "深德天麻鱼头火锅(宝珠东路店)",
    "Branch": "",
    "District": "沙溪鎮",
    "Category": "粵菜",
    "Highlight": "深中通道開通後必去老店，天麻魚頭、燒鵝、黃皮仔炒雞馳名",
    "Description": "深中通道開通後最值得去的老店，位於沙溪鎮內，以本地人為主要食客。每天中午一開門就有食客等候第一爐燒鵝出爐。招牌天麻魚頭燉湯滋補鮮美，黃皮仔炒雞清香開胃，其他菜品同樣出色。",
    "Address": "中山市宝珠东路162号",
    "Avg_Cost": "55",
    "Amap_URL": "https://surl.amap.com/9JiEZNEbf7U",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "147",
    "Restaurant_Name": "神岸餐吧",
    "Branch": "",
    "District": "神灣鎮",
    "Category": "西式",
    "Highlight": "神灣堡廣場希臘風情餐吧，烤雞、牛排、Pizza、爆肉串燒全備，日落江景絕美",
    "Description": "位於神灣堡廣場的特色餐吧，環境活如希臘小屋，滿眼綠意與波光粼影。白天可嘆下午茶，夜晚微醺爐端燒美式Barbecue。主打烤雞、牛排、Pizza及爆肉串燒等美式燒烤，海邊日落景色絕美。深中通道開通後神灣鎮新地標，適合下午茶、閨蜜小聚、夜晚微醺。",
    "Address": "中山市神湾大道中与围仔街交叉口西北60米",
    "Avg_Cost": "120",
    "Amap_URL": "https://surl.amap.com/aQyjetQO8nk",
    "Status": "https://youtu.be/ZNZeutgNTEE?si=9JW_NNlKNxSaG7A8",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "148",
    "Restaurant_Name": "炭記囍筷",
    "Branch": "",
    "District": "港口鎮",
    "Category": "燒烤",
    "Highlight": "青玉立坊文創園炭爐烤肉，人均¥60，氛圍感十足",
    "Description": "位於港口鎮青玉立坊文創園的特色炭爐烤肉餐廳，2023年9月入駐，主理人梁文鏗（鏗少）主打炭爐烤肉，乾料特別香，配搭西柚綠茶一流。園區文藝氛圍濃厚，與周邊商家緊密聯動。深中通道開通後港口鎮新晉打卡地，適合朋友聚餐、夜晚微醺。",
    "Address": "广东省中山市港口镇民昌路六号(青玉立坊)",
    "Avg_Cost": "60",
    "Amap_URL": "https://surl.amap.com/1N15BiS1565q",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "149",
    "Restaurant_Name": "廣漪燒鳥",
    "Branch": "東區店",
    "District": "東區",
    "Category": "日式料理",
    "Highlight": "大眾點評東區燒烤熱門榜第4名，深夜宵夜首選，人均¥78",
    "Description": "廣漪燒鳥東區分店，位於鰲長公路東城里南門口（東城里牌坊下），深夜宵夜熱門打卡地，每日17:30至凌晨2:00營業。招牌菜：紫蘇帶皮雞、生蠔、焦糖菠蘿、五花肉紫蘇包蝦、帶子、鸡软骨、雪花牛肋。深中通道開通後東區人氣宵夜店，週末常見排隊。",
    "Address": "中山市鳌长公路29号之3号",
    "Avg_Cost": "78",
    "Amap_URL": "https://surl.amap.com/7x8WjOyccHs",
    "Status": "",
    "Youtube": "https://youtu.be/4EjVTBy-DRk?si=dpZXv1vghXMBxM07",
    "sortbydate": ""
  },
  {
    "ID": "150",
    "Restaurant_Name": "柒弦 ORACLE Piper",
    "Branch": "",
    "District": "石岐區",
    "Category": "星馬菜",
    "Highlight": "中山唯一正宗娘惹菜，回流華僑主理，肉骨茶、叻沙一流",
    "Description": "由回流星馬華僑主理，主打正宗新加坡娘惹菜，裝修充滿星馬南洋風情，設有閣樓。招牌菜包括馬來慢燉牛肉咖喱、瑪莎拉優格雞、檳城阿叁叻沙、番茄煙肉鍋及炸雞翅。週一至五午市及晚市均有營業，週末全日開放。",
    "Address": "中山市天明花园C区东南门西80米",
    "Avg_Cost": "41-100",
    "Amap_URL": "https://surl.amap.com/81Zbcb8A428",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "151",
    "Restaurant_Name": "逢年餐廳",
    "Branch": "花園新村店",
    "District": "東區",
    "Category": "農家菜",
    "Highlight": "獨棟別墅改建的家常菜餐廳，環境優美，菜品清淡樸實，人均¥110",
    "Description": "藏於中山東區花園新村的獨棟別墅家常菜餐廳，環境優美清雅，有家的感覺。主打粵式農家菜，菜品清清淡淡，用料新鮮，招牌菜包括煎藕餅、臘肉三拼、香菇蒸肉餅、金線蓮燉老鴨、花旗參燉烏雞、炒菜心、紅葱頭雞等。在中山已開多年，深受本地街坊喜愛。",
    "Address": "中山市東區街道華苑大街3橫巷花園新村20號之2",
    "Avg_Cost": "110",
    "Amap_URL": "https://surl.amap.com/7At6HCq1f1Tb",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "152",
    "Restaurant_Name": "孫奇珍茶樓",
    "Branch": "",
    "District": "石岐區",
    "Category": "粵菜",
    "Highlight": "復刻石岐百年老字號，騎樓建築內品潮粵式早茶，人均¥100內",
    "Description": "孫奇珍茶樓復刻1912年孫中山同族遠親孫宏業創立的奈珍茶樓，曾是石岐最大茶樓。位於孫文西路步行街舊僑商建築內，騎樓風格充滿民國氣息。主打粵式早茶茶點，招牌菜包括雞蛋滑肉餅、蝶蝶餅、鮮蝦菠菠餅、石岐乳鴿、參湯蝦餅等。單日營收超四萬元，是孫文西路步行街最火爆的景點之一。",
    "Address": "中山市孙文西路文化旅游步行街102-104号",
    "Avg_Cost": "100內",
    "Amap_URL": "https://surl.amap.com/3KDqaI2ueQ6",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "153",
    "Restaurant_Name": "千瑞·西式簡餐·獨棟小院",
    "Branch": "",
    "District": "石岐區",
    "Category": "西式",
    "Highlight": "獨棟小院花園餐廳，法式浪漫氛圍，叻沙意粉、日式鰻魚炒飯為招牌",
    "Description": "位於石岐悅華小區的獨棟別墅餐廳，一進門即見精緻小院，大大蝴蝶結背景牆極具打卡感。風格簡約舒適，窗台位用餐寫意。招牌菜包括叻沙忌廉意粉、日式鰻魚炒飯、娘惹沙拉肉意麵、廉揭魷魚鬚及夕柚氣泡水。評分 4.7，環境評分 4.8，是石岐區熱門約會及拍照勝地。",
    "Address": "中山市石岐街道悅來南路悅華小區悅華街11號樓",
    "Avg_Cost": "60",
    "Amap_URL": "https://surl.amap.com/82NhQ2C14buC",
    "Status": "",
    "Youtube": "https://youtube.com/shorts/GhEdooIfL0g?si=OCCyElYsF3sS8rq5",
    "sortbydate": ""
  },
  {
    "ID": "154",
    "Restaurant_Name": "沙溪佬食店",
    "Branch": "福生東街店",
    "District": "沙溪鎮",
    "Category": "粵菜",
    "Highlight": "百年傳承一品燒鵝，沙溪鎮街坊酒樓首選，人均¥60",
    "Description": "沙溪鎮人氣街坊酒樓，位於福生東街，深受附近居民喜愛。招牌菜一品燒鵝（例牌¥38）、沙薑咸雞（半隻¥33）、煎釀三寶（¥30）、拍薑蒸淋順鱸魚（¥39），价錢實惠。燒鵝百年傳承，鵝紅、沙溪香芋扣肉、小欖炸魚球同樣出色。深中通道開通後港人必去打卡點，每日中午開門就有食客等候第一爐燒鵝出爐。",
    "Address": "中山市沙溪鎮雲漢福生東街6號",
    "Avg_Cost": "60",
    "Amap_URL": "https://surl.amap.com/9Jo7bxE1x4Cb",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "155",
    "Restaurant_Name": "泰好運泰式大排檔",
    "Branch": "",
    "District": "東區",
    "Category": "泰式料理",
    "Highlight": "大眾點評中山泰菜熱門榜第1名，盛景尚峰對面，正宗泰式大排檔風格，人均¥75",
    "Description": "中山東區人氣泰式餐廳，位於盛景尚峰對面東裕路80號二樓，大眾點評中山泰菜熱門榜第1名。餐廳裝修泰式大排檔風，熱鬧熱鬧。招牌菜包括冬陰功湯、咖喱蟹、綠咖喱雞、蝦醬秋葵、木瓜鳳爪沙律。泰式風味濃郁，較香港泰菜辣，深受港人喜愛。每日時常有排隊，建議提前訂位。",
    "Address": "中山市東區街道東裕路80號二樓",
    "Avg_Cost": "75",
    "Amap_URL": "https://surl.amap.com/7yeJlKa1m5PO",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "156",
    "Restaurant_Name": "COMMUNE幻師",
    "Branch": "興中廣場店",
    "District": "石岐區",
    "Category": "西式",
    "Highlight": "連鎖餐酒吧，金沙雞翼、麻婆豆腐Pizza又抵又好食，人均¥80",
    "Description": "COMMUNE幻師興中廣場店，位於石岐鳳鳴路3號興中廣場B2-1F03室，係全國知名餐酒吧連鎖品牌。雖然係連鎖，但食物質素出色，性價比高。必試金沙雞翼（脆脆金沙翅）及麻婆豆腐Pizza，味道驚喜，食客評語「初時擔心伏，結果無事，可以成個食哂」。環境chill，氛圍感十足，適合朋友聚會或小酌。",
    "Address": "中山市石岐街道鳳鳴路3號興中廣場B2-1F03室",
    "Avg_Cost": "80",
    "Amap_URL": "https://surl.amap.com/83lNkka136dj",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "157",
    "Restaurant_Name": "輪子商店",
    "Branch": "",
    "District": "西區",
    "Category": "咖啡 Chill 地方",
    "Highlight": "彩虹大道ART創意園隱世咖啡店，日式咖哩、焦糖香蕉可麗餅打卡必試，人均¥70",
    "Description": "藏於西區彩虹大道ART創意園E區14號的隱世咖啡小店，環境裝修靚，充滿文藝氣息。主打日式咖哩飯及各式輕食，招牌菜包括豚肉咖喱飯、蘇紫豚肉乳酪卷、焦糖香蕉可麗餅、炸厚切牛排、炸黑虎蝦蝦及布丁。咖啡中山風格，比較淡。適合午市輕鬆用餐，是西區打卡新熱點。營業時間周二至周日09:30-17:30。",
    "Address": "中山市西區街道彩虹大道16號ART創意園E區14號",
    "Avg_Cost": "70",
    "Amap_URL": "https://surl.amap.com/91qXbhc1qb7x",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "158",
    "Restaurant_Name": "daydreamer pâtisserie",
    "Branch": "",
    "District": "西區",
    "Category": "法式甜品",
    "Highlight": "中山法甜榜首，日系風格甜品店，蜂蜜鮮乳卷、葡萄煎茶必試，人均¥70",
    "Description": "中山西區黃金廣場人氣法式甜品店，位於翠景道雅居樂劍橋郡睿爵五區4棟41卡，大眾點評評分4.4，中山法甜界口碑與人氣一如既往穩居榜首。2025年3.0版本重磅回歸，裝修全新升級。招牌甜品包括蜂蜜鮮乳卷、葡萄煎茶、新綠蛋糕、焦糖乳酪鳳梨卷、草莓卷、泰茶及木糠芝士卷。日系甜品風格，甜度適中，深受港人喜愛，是西區必去打卡甜品店。",
    "Address": "中山市西區翠景道雅居樂劍橋郡睿爵五區4棟41卡",
    "Avg_Cost": "70",
    "Amap_URL": "https://surl.amap.com/9ffS3SW1qdMG",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "159",
    "Restaurant_Name": "松本壽司工坊（紫馬店）",
    "Branch": "",
    "District": "東區",
    "Category": "日式料理",
    "Highlight": "大眾點評中山壽司好評榜第1名，紫馬廣場二樓，厚燒法國鵝肝壽司、三文魚魚腩刺身必試，人均¥100",
    "Description": "中山東區紫馬廣場一期2F-05室人氣日料壽司店，大眾點評中山壽司好評榜第1名，評分高達4.8，被食客譽為「中山第二好吃的壽司店」。位於盛景尚峰對面，交通方便。招牌菜包括馬鈴薯沙拉、三文魚壽司、厚燒法國鵝肝壽司、三文魚魚腩刺身、厚切鰻魚壽司、刺身拼盤、馬糞海膽壽司、鵝肝醬伴芒果壽司、紅酒鵝肝軍艦及黑松露甜蝦壽司。每款壽司用料講究，性價比高，是東區日料愛好者必去之選。",
    "Address": "中山市中山五路2号紫马奔腾二楼",
    "Avg_Cost": "100",
    "Amap_URL": "https://surl.amap.com/7ygUsr01A2xD",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "160",
    "Restaurant_Name": "海悅軒·The Vegan Kitchen",
    "Branch": "",
    "District": "石岐區",
    "Category": "素食",
    "Highlight": "大眾點評中山素食好評榜第1名，東方海悅酒店6樓，開業逾10年，新派創意素食，人均¥70",
    "Description": "中山石岐區安欄路162號東方海悅酒店6樓，大眾點評中山素食好評榜第1名，開業逾10年，是中山最具口碑的素食餐廳。2014年全面轉型為素食餐廳，以新派創意素食為主，菜品有新意有特點，深受食客好評。午市提供自助式午餐，晚市提供多款套餐選擇。環境優雅，位置近岐江公園，交通便利。適合素食者、養生人士及希望嘗試健康飲食的食客。",
    "Address": "中山市石岐區安欄路162號東方海悅酒店6樓",
    "Avg_Cost": "70",
    "Amap_URL": "https://surl.amap.com/84HQDge152AP",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "161",
    "Restaurant_Name": "麥提爽·澳門生麵",
    "Branch": "東區店",
    "District": "東區",
    "Category": "麵食",
    "Highlight": "澳門人主理，大地魚湯底鮮香清甜，澳門豬扒麵、蠔仔紫菜湯必試，人均¥40以下",
    "Description": "中山東區南下新碼頭槎橋路13號瀚華花園35卡之一，澳門人主理的港澳風味麵店，店名取自TVB劇集黃子華的角色。主打澳門生麵，可選生麵、粗麵、薄荷粉、米粉，可選湯上或乾撈，配大地魚湯、咖喱汁撈，湯底鮮香清甜。招牌菜澳門豬扒、蠔仔紫菜湯、招牌蝦子，另有套餐（1麵1菜1飲品）性價比極高。紅豆冰有童年回憶，食飯時間常需等位。",
    "Address": "中山市东区街道槎桥路13号瀚华花园16卡",
    "Avg_Cost": "40以下",
    "Amap_URL": "https://surl.amap.com/7C7JMxQBbX1",
    "Status": "",
    "Youtube": "https://youtube.com/shorts/yGgA5N-cND4?si=L1QAZo2-SbNsxlpJ",
    "sortbydate": ""
  },
  {
    "ID": "162",
    "Restaurant_Name": "素囍蔬食主題餐廳（維景灣店）",
    "Branch": "",
    "District": "東區",
    "Category": "素食",
    "Highlight": "中山東區人氣素食餐廳，環境清雅如古堡森林，創意蔬食菜式令人驚喜",
    "Description": "素囍蔬食主題餐廳位於東區維景灣商業街，外立面如古堡森林，環境清幽淡雅，即使坐大廳也不會嘈雜，適合帶家人或朋友一起享用健康素食。主打創意蔬食菜式，菜色豐富多樣，定期推出季節限定新菜，招牌菜有牛油果薑蓉炒飯、黑椒素扒、素囍冬陰功、蔓越莓梳乎厘燒賣、芝士焗迷你薯等。二樓設茶位（另加10%服務費），適合素食者及養生人士。",
    "Address": "中山市東區街道維景灣商業街二期11-12卡1-3層",
    "Avg_Cost": "90",
    "Amap_URL": "https://surl.amap.com/7ADqzPQmenB",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "163",
    "Restaurant_Name": "飯糖",
    "Branch": "",
    "District": "東區",
    "Category": "韓國菜",
    "Highlight": "復古食堂風格，韓式定食配中式糖水，中山獨特混血美食體驗",
    "Description": "飯糖位於中山東區翠盈街2號，是一家充滿復古溫馨社區風格的小食堂。店內以木製家具、傳統陶瓷器皿及暖色燈光打造出濃濃的家的味道，牆上掛著「飯香滿屋、幸福滿滿」的招牌。主打韓式定食，配以多款小菜（泡菜、豆芽、鵪鶉蛋等），招牌菜包括韓式拌飯、石鍋燉菜、烤鯖魚定食及青花魚定食。最大特色是韓式定食與中式糖水的融合，吃完鹹食可直接享用一碗中式糖水，在中山屬相當新穎的搭配。店主用心，裝飾文字設計獨具風格，每一處細節都透露著巧思。",
    "Address": "饭糖 翠兴街与兴中道交叉口东北40米",
    "Avg_Cost": "40以下",
    "Amap_URL": "https://surl.amap.com/7Cm5jqGU28v",
    "Status": "",
    "Youtube": "https://youtube.com/shorts/P77OKswU1rY?si=1cYy0ckaXx3gr5SW",
    "sortbydate": ""
  },
  {
    "ID": "164",
    "Restaurant_Name": "Kapin x Note Coffee",
    "Branch": "",
    "District": "三鄉鎮",
    "Category": "咖啡 Chill 地方",
    "Highlight": "橋頭村稻田玻璃屋咖啡館，180°無遮擋稻田景，Chill 放電好去處",
    "Description": "Kapin x Note Coffee（咔品花茶 x 咖啡筆記）位於中山三鄉橋頭村麥園下街，是一間擁有巨型落地玻璃的稻田咖啡館。坐在店內可欣賞 180° 無遮擋的翠綠稻田景色，環境寧靜悠閒，是放電 Chill 的絕佳選擇。招牌有彩虹巴斯克蛋糕（芝士、朱古力、開心果、彩虹慕絲四款口味）、蜜桃烏龍冷萃、椰青檸檬茶等。離開時可順道幫襯村邊伯伯的新鮮蔬果攤，感受地道農村生活。",
    "Address": "廣東省中山市三鄉鎮橋頭村麥園下街137號",
    "Avg_Cost": "40",
    "Amap_URL": "https://surl.amap.com/a5JOIua17dyn",
    "Status": "",
    "Youtube": "https://youtube.com/shorts/HUqTKavSu8M?si=1c6O6tTO7F5mHjem",
    "sortbydate": ""
  },
  {
    "ID": "165",
    "Restaurant_Name": "苏洽料理",
    "Branch": "",
    "District": "東區",
    "Category": "日式料理",
    "Highlight": "12種湯底日式拉麵，老闆香港人，可要求調整鹹度",
    "Description": "藏在 Bos Park 附近的低調日式拉麵店，餐廳名稱取自英文 Souper 的廣東話釋音。室內位不多，另設露天平台。最大特色是提供足足 12 種不同湯底的拉麵，總有一款啱你。老闆是香港人，老闆娘是中山人，口味偏向本地後生仔喜好，湯底可能偏鹹，建議落單時跟老闆說一聲唔想咁鹹，佢哋好樂意調整，咁啲拉麵就會啱啱好啱你胃口。",
    "Address": "中山市東區紫岭街道東路9號園區B棟二層（Bos Park 2F）",
    "Avg_Cost": "100",
    "Amap_URL": "https://surl.amap.com/aKd47ZI1AajW",
    "Status": "",
    "Youtube": "https://youtube.com/shorts/ry8O9aY8VXU?si=cJtqla5l1FzwaM7L",
    "sortbydate": ""
  },
  {
    "ID": "166",
    "Restaurant_Name": "NoDo",
    "Branch": "",
    "District": "石岐區",
    "Category": "日式料理",
    "Highlight": "石岐區日本拉麵餐廳，位於岐創數字文化產業園內",
    "Description": "石岐區的日本拉麵餐廳，隔隔地在岐創數字文化產業園內。提供多種日式拉麵，適合喜歡日式食物的食客。",
    "Address": "中山市石岐街道清溪路18號岐創數字文化產業園",
    "Avg_Cost": "待詢",
    "Amap_URL": "https://surl.amap.com/7MkA2PopfD8",
    "Status": "",
    "Youtube": "",
    "sortbydate": "2026/7/18"
  },
  {
    "ID": "167",
    "Restaurant_Name": "麺処藤本家（石岐總店）",
    "Branch": "",
    "District": "石岐區",
    "Category": "日式料理",
    "Highlight": "日式拉麵，追求正宗日本風味，常客回頭率高",
    "Description": "石岐區人氣日式拉麵店，追求正宗日本風味。提供秘制味噌湯拉麵、和風海鹽清湯拉麵、和風醬油清湯拉麵、黑蒜濃厚豚骨拉麵、赤辛濃厚豚骨拉麵等多種口味。注意：湯底偏鸹，屬日式傳統風格，如不喜太鸹可向店員討論。",
    "Address": "中山市石岐街道逢源路5號31卡",
    "Avg_Cost": "60",
    "Amap_URL": "https://surl.amap.com/7NiBo26S9hE",
    "Status": "",
    "Youtube": "https://youtube.com/shorts/frH8VawENcM?si=syZhIcm-vw3_reJj",
    "sortbydate": ""
  },
  {
    "ID": "168",
    "Restaurant_Name": "山野食堂",
    "Branch": "",
    "District": "石岐區",
    "Category": "日式料理",
    "Highlight": "北海道森林風格小店，環境氛圍極佳，人氣簡餐",
    "Description": "石岐區人氣簡餐店，裝修風格有點北海道森林小木屋感覺，室內外共約20個餐位，音樂特別好聽，環境分拉滿。招牌菜包括山野秘製雞翅、炙烤黃油大蝦配冬蔭公湯、蝦頭油海鮮炒飯等。整體環境很好，出品不錯，人氣旺盛，不少博主強推。",
    "Address": "中山市東區街道柏苑新村紫荊閣1幢2卡商鋪",
    "Avg_Cost": "60-100",
    "Amap_URL": "https://surl.amap.com/86fl2OKd506",
    "Status": "",
    "Youtube": "https://youtube.com/shorts/I47Hln1dy_k?si=85Bq68aF8FFGJVT_",
    "sortbydate": ""
  },
  {
    "ID": "169",
    "Restaurant_Name": "意桥餐厅 (Il Ponte)",
    "Branch": "",
    "District": "東區",
    "Category": "西式",
    "Highlight": "58 樓高空全景，浪漫約會首選",
    "Description": "位於利和希爾頓酒店 58 樓，坐擁俯瞰全市的壯麗景觀。主打地道義式料理與精緻排餐，環境優雅安靜，是慶祝紀念日與享受高空夜景的頂級餐飲地標。",
    "Address": "中山市東區中山三路 16 號，中山利和希爾頓酒店 58 樓",
    "Avg_Cost": "300-600",
    "Amap_URL": "https://surl.amap.com/1NkQ5Cm1b0jx",
    "Status": "",
    "Youtube": "",
    "sortbydate": "2026/7/18"
  },
  {
    "ID": "170",
    "Restaurant_Name": "囍尚佳窑 (石岐萬科店)",
    "Branch": "",
    "District": "石岐區",
    "Category": "粵菜",
    "Highlight": "市區大隱於市的「荔枝柴」窯烤，現代舒適環境。",
    "Description": "位於石岐萬科金域藍灣，將南朗地道窯雞帶入城市生活。招牌窯雞選用本地三黃雞，經高溫窯製皮脆多汁，更提供精緻粵菜與小炒。裝修時尚大氣，是市區內與親友品嚐傳統燒烤風味的最佳選擇。",
    "Address": "中山市石岐街道青溪路140号一层之三118",
    "Avg_Cost": "85 - ￥115",
    "Amap_URL": "https://surl.amap.com/4KQPeuGGb7n",
    "Status": "",
    "Youtube": "",
    "sortbydate": "2026/7/18"
  },
  {
    "ID": "171",
    "Restaurant_Name": "噏耷茶檔",
    "Branch": "",
    "District": "石岐區",
    "Category": "港式茶餐廳",
    "Highlight": "懷舊復古裝潢，特色「手打檸檬茶」與港式小食",
    "Description": "隱藏在石岐舊區街弄內的懷舊茶檔，以復古磁磚與霓虹燈營造濃厚港味。主打手打檸檬茶、一口西多士及各類港式麵食。店名「噏耷」自嘲簡陋，實則環境隨意寫意，是當地年輕人下午茶與深夜閒聊的人氣聚點。",
    "Address": "中山市興業街 3 號首層",
    "Avg_Cost": "40 - ￥60",
    "Amap_URL": "https://surl.amap.com/1Og6k58Ef1r",
    "Status": "",
    "Youtube": "https://www.youtube.com/shorts/AFdBdtTgHJ8",
    "sortbydate": ""
  },
  {
    "ID": "172",
    "Restaurant_Name": "HEE (星月居店)",
    "Branch": "",
    "District": "東區",
    "Category": "港式輕食 / 咖啡",
    "Highlight": "必食神級粟米肉粒飯、秘制經典厚切焗豬扒飯，大廚香港人",
    "Description": "披著極簡咖啡店外殼的實力派餐館。網民激推其「神級」粟米肉粒飯，芡汁濃郁肉質嫩滑；焗豬扒飯則充滿昔日港式快餐的懷舊風味。這裡將精品咖啡與高水準港式主食完美結合，是東區極具反差魅力的打卡美食地標。",
    "Address": "中山市體育橫街與華夏街交叉口東 20 米",
    "Avg_Cost": "50 - ￥80",
    "Amap_URL": "https://surl.amap.com/1OXdhhQu13W",
    "Status": "",
    "Youtube": "https://youtube.com/shorts/upIq5Vf5XWw?si=uSgGOn_8V7XUhUdy",
    "sortbydate": ""
  },
  {
    "ID": "173",
    "Restaurant_Name": "廣老表鲜切现烫牛肉粉(柏苑店)",
    "Branch": "",
    "District": "石岐區",
    "Category": "特色小食 / 麵粉類",
    "Highlight": "現切鮮牛肉、秘製香濃牛骨湯底",
    "Description": "位於石岐舊城區的多年老店，是無數中山人的集體回憶。主打現點現做的鮮牛肉粉，牛肉鮮嫩滑溜，搭配熬製多時的濃郁湯底，每一口都是道地的石岐情懷。其親民的價格與穩定的水平，使其成為老城區必試的街坊食堂。",
    "Address": "中山市柏苑新村东2门旁",
    "Avg_Cost": "15 - ￥25",
    "Amap_URL": "https://surl.amap.com/1W9aMiS159C8",
    "Status": "",
    "Youtube": "https://youtube.com/shorts/y75Ax9sbaAk?si=Nns7ty7tDLgb31gA",
    "sortbydate": ""
  },
  {
    "ID": "174",
    "Restaurant_Name": "螞蟻洞首爾烤肉",
    "Branch": "富逸城店",
    "District": "火炬開發區",
    "Category": "韓國菜",
    "Highlight": "2026中山排隊王，首爾露營風極致體驗",
    "Description": "深中通道開通後火爆全城的富逸城TopPark人氣首店。以首爾露營風為主題，招牌厚切豬五花與菠蘿牛肋條極具特色，全程代烤服務深得港澳食客歡心。",
    "Address": "中山市火炬開發區孫文東路686號富逸城TopPark L4層",
    "Avg_Cost": "110",
    "Amap_URL": "https://surl.amap.com/hCErvGilgCF",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "175",
    "Restaurant_Name": "芸山季·雲南野生菌火鍋",
    "Branch": "富逸城店",
    "District": "火炬開發區",
    "Category": "雲貴川菜",
    "Highlight": "2026高端養生局必備，鮮掉眉毛的野生菌湯",
    "Description": "強勢進駐中山全新地標富逸城TopPark的火鍋天花板。主打空運鮮菌與土雞熬製的靈魂湯底，松茸、竹蓀口感極致鮮美，環境優雅靜謐，是高端聚餐新寵。",
    "Address": "中山市火炬開發區孫文東路686號富逸城TopPark L5層",
    "Avg_Cost": "135",
    "Amap_URL": "https://surl.amap.com/hDctCWC32is",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "176",
    "Restaurant_Name": "南成行",
    "Branch": "從善坊店",
    "District": "石岐區",
    "Category": "星馬菜",
    "Highlight": "百年僑房沉浸式體驗，正宗南洋娘惹文化",
    "Description": "2025至2026年隨著香山古城活化而極速爆紅的網紅店。由百年老房改造的馬來西亞娘惹菜餐廳，店內陳列峇峇娘惹老物件，完美復刻地道南洋風味。",
    "Address": "中山市石岐街道從善坊歷史文化街區18、20號",
    "Avg_Cost": "80",
    "Amap_URL": "https://surl.amap.com/hBOEOcO59Zk",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "177",
    "Restaurant_Name": "泉光小院",
    "Branch": "",
    "District": "石岐區",
    "Category": "咖啡 Chill 地方",
    "Highlight": "從善坊百年老街活化，巷子深處靜謐茶舍",
    "Description": "隨著從善坊歷史文化街區全面活化而爆紅的隱世茶舍。藏在巷子深處，提供極致寧靜的中式茶飲與精緻茶點，是2026年慢生活與拍照的絕佳地。",
    "Address": "中山市石岐街道從善坊歷史文化街區",
    "Avg_Cost": "50",
    "Amap_URL": "https://surl.amap.com/hClIvn4WfOs",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "178",
    "Restaurant_Name": "珠瓏入水·手作糖水",
    "Branch": "天奕星河店",
    "District": "東區",
    "Category": "甜品",
    "Highlight": "2026強勢霸榜，取「豬籠入水」好意頭的創意糖水",
    "Description": "從中山發跡並火遍灣區的新中式糖水。以順德水牛奶、荔浦香芋等天然食材每天新鮮現做。店內佈置手工竹編與綠植，大滿貫芋圓是必點招牌。",
    "Address": "中山市東區街道中山六路1號天奕星河COCOCity L4",
    "Avg_Cost": "35",
    "Amap_URL": "https://surl.amap.com/hBWY45Y1vd67",
    "Status": "",
    "Youtube": "https://www.youtube.com/watch?v=IhVTA4F3qQc",
    "sortbydate": ""
  },
  {
    "ID": "179",
    "Restaurant_Name": "左咖啡",
    "Branch": "左步村店",
    "District": "南朗鎮",
    "Category": "咖啡 Chill 地方",
    "Highlight": "週末微度假打卡熱點，百年老宅改建的鄉村咖啡",
    "Description": "位於名人輩出的左步村內，利用閒置老宅精心改建。保留了青磚瓦頂與復古傢俱，手繪牆與優雅燈飾交相輝映，充滿獨特鄉村風情與文藝氣息。",
    "Address": "中山市南朗鎮左步村中興里巷25號",
    "Avg_Cost": "40",
    "Amap_URL": "https://surl.amap.com/hCvbVLAu0DR",
    "Status": "",
    "Youtube": "https://www.youtube.com/watch?v=-KUHg5jpoGM",
    "sortbydate": ""
  },
  {
    "ID": "180",
    "Restaurant_Name": "耀榮食店·橫門鯽魚粥",
    "Branch": "",
    "District": "南朗鎮",
    "Category": "粥麵小食",
    "Highlight": "橫門市場旁的隱世寶藏，老饕強推的鮮甜鯽魚粥",
    "Description": "裝修極度樸實無華的街坊小店，卻在2026年被無數美食博主挖掘。主打新鮮熬製的橫門鯽魚粥，魚肉鮮嫩無刺感，粥底綿密清甜，本地人的私藏飯堂。",
    "Address": "中山市南朗鎮海富北路橫門市場北側約110米",
    "Avg_Cost": "45",
    "Amap_URL": "https://surl.amap.com/hCDbSZc1kdBe",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "181",
    "Restaurant_Name": "啫火啫啫煲",
    "Branch": "石岐萬象匯店",
    "District": "石岐區",
    "Category": "粵菜",
    "Highlight": "萬物皆可啫，廣府鑊氣天花板",
    "Description": "2026年人氣高企的廣式啫啫煲專門店。以猛火乾燒、砂鍋上桌的極致鑊氣聞名，招牌啫啫走地雞、啫啫大腸香氣撲鼻，是港澳客感受正宗廣府火候的必吃榜。",
    "Address": "中山市石岐街道孫文東路28號石岐萬象匯L4層L419號鋪",
    "Avg_Cost": "95",
    "Amap_URL": "https://surl.amap.com/hJwNFtw1bgNZ",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "182",
    "Restaurant_Name": "春華園華僑主題餐廳",
    "Branch": "",
    "District": "石岐區",
    "Category": "粵菜",
    "Highlight": "華僑公園內綠植環繞, 小橋流水",
    "Description": "隱藏在華僑公園內的華僑主題茶樓。環境寧靜愜意，綠植與小橋流水造景相映成趣，是品飲早茶、感受悠閒時光的網紅打卡新地標。",
    "Address": "中山市石岐街道華僑公園內",
    "Avg_Cost": "85",
    "Amap_URL": "https://surl.amap.com/adgdampH7rO",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "183",
    "Restaurant_Name": "大榕樹下·順德菜",
    "Branch": "富逸城店",
    "District": "火炬開發區",
    "Category": "順德菜",
    "Highlight": "招牌豉味碌鵝, 順德地道風味",
    "Description": "進駐富逸城TopPark的人氣順德菜。招牌豉味碌鵝醬汁濃郁、肉質鮮嫩，陳村粉與撈雞同樣極具水準，是商場內高性價比的粵菜排隊熱店。",
    "Address": "中山市火炬開發區孫文東路686號富逸城L4層JL4-28號鋪",
    "Avg_Cost": "80",
    "Amap_URL": "https://surl.amap.com/iZTPHdUHeAn",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "184",
    "Restaurant_Name": "有得飽·乾炒牛河",
    "Branch": "富逸城店",
    "District": "火炬開發區",
    "Category": "粥麵小食",
    "Highlight": "中山最勁乾炒牛河, 鑊氣十足",
    "Description": "主打古老手工沙河粉的乾炒牛河專門店。牛肉滑嫩、鑊氣十足，還有薑蔥炒豬雜及各類廣式手工點心，被食客譽為中山乾炒牛河天花板。",
    "Address": "中山市火炬開發區孫文東路686號富逸城L4-02號商舖",
    "Avg_Cost": "50",
    "Amap_URL": "https://surl.amap.com/1mk4MvM112cPS",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "185",
    "Restaurant_Name": "文通冰室",
    "Branch": "富逸城店",
    "District": "火炬開發區",
    "Category": "港式茶餐廳",
    "Highlight": "黯然銷魂飯, 濃郁港式風味",
    "Description": "人氣爆棚的港式茶餐廳，招牌黯然銷魂飯與牛肉醬焗意粉廣受好評。花旗參燉烏雞湯火候十足，搭配正宗港式凍檸茶，港味還原度極高。",
    "Address": "中山市火炬開發區孫文東路686號富逸城TopPark L4層",
    "Avg_Cost": "65",
    "Amap_URL": "https://surl.amap.com/iZ5XJS213f7M",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "186",
    "Restaurant_Name": "湘辣辣",
    "Branch": "富逸城店",
    "District": "火炬開發區",
    "Category": "湘菜",
    "Highlight": "現炒花龍, 下飯神菜排隊王",
    "Description": "憑藉招牌現炒花龍（牛肉）火爆全城的湘菜排隊王。牛肉鮮嫩帶嚼勁，搭配酸菜極度惹味下飯，無辣不歡食客的必試之選。",
    "Address": "中山市火炬開發區孫文東路686號富逸城TopPark L5層",
    "Avg_Cost": "85",
    "Amap_URL": "https://surl.amap.com/j0cpTeafaBS",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "187",
    "Restaurant_Name": "泰柯茶園",
    "Branch": "",
    "District": "火炬開發區",
    "Category": "茶飲",
    "Highlight": "貓咪造型芝士奶蓋, 打卡一流",
    "Description": "主打特色奶蓋及打卡茶飲的新晉網紅店。招牌貓咪造型芝士奶蓋及爆米花特飲可愛吸睛，是逛商場必備的高顏值消暑聖品。",
    "Address": "中山市火炬開發區孫文東路686號富逸城TopPark L4層",
    "Avg_Cost": "30",
    "Amap_URL": "https://surl.amap.com/ghC489L3grH",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "188",
    "Restaurant_Name": "百草源美食坊",
    "Branch": "",
    "District": "橫欄鎮",
    "Category": "粵菜",
    "Highlight": "巨型海鲩刺身, 特色特價點心",
    "Description": "橫欄鎮深具人氣的地方食府，主打足秤新鮮的巨型海鲩刺身，肉質晶瑩爽脆。大廳每日供應多款特價廣式點心，性價比極高。",
    "Address": "中山市橫欄鎮沿江街1號",
    "Avg_Cost": "75",
    "Amap_URL": "https://surl.amap.com/j3VnEps1d9ki",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "189",
    "Restaurant_Name": "星威鴿餐廳",
    "Branch": "橫欄店",
    "District": "橫欄鎮",
    "Category": "粵菜",
    "Highlight": "招牌大盤魚, 中山馳名燒乳鴿",
    "Description": "以招牌大盤魚及特色燒鴿聞名的街坊餐廳。大盤魚份量驚人、湯底鮮甜，搭配皮脆肉嫩的乳鴿，是性價比極高的大眾飯堂。",
    "Address": "中山市橫欄鎮橫東村牌坊對面首層之一",
    "Avg_Cost": "65",
    "Amap_URL": "https://surl.amap.com/j44KMAq27X2",
    "Status": "",
    "Youtube": "",
    "sortbydate": ""
  },
  {
    "ID": "190",
    "Restaurant_Name": "ZQ·Meet轻食简餐",
    "Branch": "华柏店",
    "District": "石岐區",
    "Category": "☕ 咖啡 / 甜品輕食",
    "Highlight": "健康低卡輕食，石岐區簡餐之選",
    "Description": "【2026核實】主打健康輕食簡餐，食材新鮮適合追求輕盈飲食嘅食客，店內環境簡約舒適，係石岐區一個幾唔錯嘅簡餐落腳點。",
    "Address": "中山市石岐街道华柏路33号1-2层(107卡)",
    "Avg_Cost": "54",
    "Amap_URL": "https://surl.amap.com/d8fJJNYs85F",
    "Status": "",
    "Youtube": "https://youtu.be/NHiERPfYbbE?is=2s2r5jpILNC8U9l2",
    "sortbydate": ""
  }
];